import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createD1Repository } from './d1';
export type StoreCustomerContext = { accountId: string; customerId: string; expiresAt: string; name: string; email: string; phone: string; marketingOptIn: number; reminderOptIn: number; birthday: string; anniversary: string; occasionReminderOptIn: number };
export function customerToken(request: Request) { const value = request.headers.get('authorization') || ''; return value.startsWith('Bearer ') ? value.slice(7).trim() : ''; }
export function createCustomerSessionToken() { return randomBytes(32).toString('hex'); }
export function hashCustomerPassword(password: string) { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password, salt, 64).toString('hex')}`; }
function hexBytes(value: string) { if (!/^[0-9a-f]+$/i.test(value) || value.length % 2) return null; const bytes = new Uint8Array(value.length / 2); for (let index = 0; index < bytes.length; index += 1) bytes[index] = Number.parseInt(value.slice(index * 2, index * 2 + 2), 16); return bytes; }
export function verifyCustomerPassword(password: string, stored: string) { const [salt, hash] = String(stored || '').split(':'); const expected = hash ? hexBytes(hash) : null; if (!salt || !expected) return false; const actual = scryptSync(password, salt, 64); return expected.length === actual.length && timingSafeEqual(expected, actual); }
export async function resolveStoreCustomer(db: D1Database, request: Request, slug: string): Promise<StoreCustomerContext | null> { const token = customerToken(request); if (!token) return null; return createD1Repository(db).first<StoreCustomerContext>(`SELECT c.account_id AS accountId, c.id AS customerId, s.expires_at AS expiresAt, c.name, c.email, c.phone, c.marketing_opt_in AS marketingOptIn, c.reminder_opt_in AS reminderOptIn, c.birthday, c.anniversary, c.occasion_reminder_opt_in AS occasionReminderOptIn FROM StoreCustomerSession s JOIN StoreCustomer c ON c.account_id = s.account_id AND c.id = s.customer_id JOIN Account a ON a.id = c.account_id WHERE s.token = ? AND s.expires_at > ? AND c.active = 1 AND lower(a.store_slug) = ? AND a.plan_tier = 'elite' LIMIT 1`, [token, new Date().toISOString(), slug.toLowerCase()]); }
