import { resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function price(config: Record<string, unknown> | null, tier: string, cycle: string) { return Number(config?.[`${tier}_${cycle}_usd`] || 0); }
function pricing(config: Record<string, unknown> | null) { return Object.fromEntries(['free', 'standard', 'pro', 'elite'].map((tier) => { const monthly = tier === 'free' ? 0 : price(config, tier, 'monthly'); const yearly = tier === 'free' ? 0 : price(config, tier, 'yearly'); return [tier, { monthly, yearly, yearly_savings: Math.round((monthly * 12 - yearly) * 100) / 100 }]; })); }
export async function handleBillingBasicRequest(request: Request, db: D1Database | undefined, config: { squareApplicationId?: string; squareLocationId?: string; squareAccessToken?: string; paypalClientId?: string; paypalClientSecret?: string }): Promise<Response | null> {
  if (!db) return null; const url = new URL(request.url); if (!['/api/billing/plans', '/api/billing/select-tier', '/api/billing/checkout-session-status'].includes(url.pathname)) return null; const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); const repo = createD1Repository(db);
  if (url.pathname === '/api/billing/plans' && request.method === 'GET') { const billing = await repo.first<Record<string, unknown>>('SELECT * FROM BillingConfig ORDER BY created_at LIMIT 1'); const account = await repo.first<{ plan_tier: string }>('SELECT plan_tier FROM Account WHERE id = ?', [auth.accountId]); const current = account?.plan_tier || auth.planTier || 'free'; const values = pricing(billing); const quotes = Object.fromEntries(['monthly', 'yearly'].map((cycle) => [cycle, Object.fromEntries(['free', 'standard', 'pro', 'elite'].map((tier) => [tier, { target_tier: tier, billing_cycle: cycle, base_price: values[tier][cycle as 'monthly' | 'yearly'], credit_applied: 0, amount_due: values[tier][cycle as 'monthly' | 'yearly'], currency: String(billing?.currency || 'USD') }]))])); return json({ plan_tier: current, pricing: billing || {}, pricing_by_tier: values, payment_options: { square_enabled: Boolean(config.squareAccessToken && config.squareApplicationId && config.squareLocationId), square_application_id: config.squareApplicationId || '', square_location_id: config.squareLocationId || '', paypal_enabled: Boolean(config.paypalClientId && config.paypalClientSecret), paypal_client_id: config.paypalClientId || '' }, tier_quotes: quotes }); }
  if (url.pathname === '/api/billing/select-tier' && request.method === 'POST') { let input: Record<string, unknown> | null = null; try { input = await request.json() as Record<string, unknown>; } catch { /* invalid */ } if (String(input?.tier || '') !== 'free') return json({ error: 'Paid plans must be changed through checkout' }, { status: 400 }); await repo.run("UPDATE Account SET plan_tier = 'free' WHERE id = ?", [auth.accountId]); return json({ ok: true, plan_tier: 'free' }); }
  if (url.pathname === '/api/billing/checkout-session-status' && request.method === 'GET') { const id = String(url.searchParams.get('session_id') || '').trim(); if (!id) return json({ error: 'Missing session_id' }, { status: 400 }); const session = await repo.first<Record<string, unknown>>('SELECT target_tier, payment_status, status FROM BillingCheckoutSession WHERE id = ? AND account_id = ? LIMIT 1', [id, auth.accountId]); if (!session) return json({ error: 'Checkout session not found' }, { status: 404 }); const account = await repo.first<{ plan_tier: string }>('SELECT plan_tier FROM Account WHERE id = ?', [auth.accountId]); return json({ paid: session.status === 'paid' || session.payment_status === 'paid', plan_tier: account?.plan_tier || auth.planTier, payment_status: session.payment_status || 'unpaid', status: session.status || 'pending', target_tier: session.target_tier || null }); }
  return null;
}
