import { createD1Repository } from '../lib/d1';

type WebhookConfig = { squareWebhookSignatureKey?: string; squareWebhookUrl?: string; paypalWebhookId?: string; paypalClientId?: string; paypalClientSecret?: string; paypalEnvironment?: string };
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function paypalBase(environment: string | undefined) { return String(environment || '').trim().toLowerCase() === 'production' ? 'https://api-m.paypal.com' : 'https://api-m.sandbox.paypal.com'; }
function bytes(value: string) { try { const decoded = atob(value); return Uint8Array.from(decoded, (character) => character.charCodeAt(0)); } catch { return null; } }
function equal(left: Uint8Array, right: Uint8Array) { if (left.length !== right.length) return false; let different = 0; for (let index = 0; index < left.length; index += 1) different |= left[index] ^ right[index]; return different === 0; }
async function squareSignatureValid(body: string, signature: string, key: string, url: string) { const provided = bytes(signature); if (!provided || !key || !url) return false; const cryptoKey = await crypto.subtle.importKey('raw', new TextEncoder().encode(key), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const signed = new Uint8Array(await crypto.subtle.sign('HMAC', cryptoKey, new TextEncoder().encode(url + body))); return equal(signed, provided); }
async function paypalToken(config: WebhookConfig) { const id = String(config.paypalClientId || '').trim(); const secret = String(config.paypalClientSecret || '').trim(); if (!id || !secret) return null; const response = await fetch(`${paypalBase(config.paypalEnvironment)}/v1/oauth2/token`, { method: 'POST', headers: { authorization: `Basic ${btoa(`${id}:${secret}`)}`, 'content-type': 'application/x-www-form-urlencoded' }, body: 'grant_type=client_credentials' }); const result = await response.json() as { access_token?: unknown }; return response.ok && String(result.access_token || '').trim() ? String(result.access_token).trim() : null; }
async function reconcileRefund(db: D1Database, provider: string, eventId: string, eventType: string, identifiers: string[], status: string) { const repo = createD1Repository(db); const payment = await repo.first<{ id: string; account_id: string; order_id: string }>('SELECT id, account_id, order_id FROM StoreOrderPayment WHERE provider = ? AND provider_payment_id IN (?, ?) ORDER BY CASE WHEN provider_payment_id = ? THEN 0 ELSE 1 END LIMIT 1', [provider, identifiers[0] || '', identifiers[1] || '', identifiers[0] || '']); if (!payment) return; const inserted = await repo.run('INSERT OR IGNORE INTO PaymentWebhookEvent (id, account_id, provider, provider_event_id, event_type, created_at) VALUES (?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), payment.account_id, provider, eventId, eventType, new Date().toISOString()]); if (Number(inserted.meta.changes || 0) !== 1) return; const now = new Date().toISOString(); await repo.run('UPDATE StoreOrderPayment SET status = ?, updated_at = ? WHERE id = ? AND account_id = ?', [status, now, payment.id, payment.account_id]); if (status === 'refunded') await repo.run("UPDATE StoreOrder SET status = 'refunded', payment_status = 'refunded', fulfillment_status = 'cancelled', updated_at = ? WHERE id = ? AND account_id = ?", [now, payment.order_id, payment.account_id]); }

export async function handlePaymentWebhookRequest(request: Request, db: D1Database | undefined, config: WebhookConfig): Promise<Response | null> {
  if (!db || request.method !== 'POST') return null; const path = new URL(request.url).pathname; if (!['/api/webhooks/square', '/api/webhooks/paypal'].includes(path)) return null;
  try {
    const body = await request.text(); const event = JSON.parse(body) as Record<string, any>;
    if (path.endsWith('/square')) {
      const valid = await squareSignatureValid(body, request.headers.get('x-square-hmacsha256-signature') || '', String(config.squareWebhookSignatureKey || '').trim(), String(config.squareWebhookUrl || '').trim()); if (!valid) return json({ error: 'Invalid Square webhook signature' }, { status: 403 });
      const eventType = String(event.type || ''); const refund = event.data?.object?.refund; if (eventType === 'refund.updated' && refund?.id) { const providerStatus = String(refund.status || '').toUpperCase(); await reconcileRefund(db, 'square', String(event.event_id || refund.id), eventType, [String(refund.id), String(refund.payment_id || '')], providerStatus === 'COMPLETED' ? 'refunded' : providerStatus === 'FAILED' ? 'refund_failed' : 'refund_pending'); }
      return json({ received: true });
    }
    const webhookId = String(config.paypalWebhookId || '').trim(); const token = await paypalToken(config); if (!webhookId || !token) return json({ error: 'PayPal webhooks are not configured' }, { status: 403 });
    const response = await fetch(`${paypalBase(config.paypalEnvironment)}/v1/notifications/verify-webhook-signature`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify({ auth_algo: request.headers.get('paypal-auth-algo'), cert_url: request.headers.get('paypal-cert-url'), transmission_id: request.headers.get('paypal-transmission-id'), transmission_sig: request.headers.get('paypal-transmission-sig'), transmission_time: request.headers.get('paypal-transmission-time'), webhook_id: webhookId, webhook_event: event }) }); const verified = await response.json() as { verification_status?: unknown }; if (!response.ok || verified.verification_status !== 'SUCCESS') return json({ error: 'Invalid PayPal webhook signature' }, { status: 403 });
    if (String(event.event_type || '') === 'PAYMENT.CAPTURE.REFUNDED' && event.resource?.id) await reconcileRefund(db, 'paypal', String(event.id || event.resource.id), String(event.event_type), [String(event.resource.id), ''], 'refunded'); return json({ received: true });
  } catch { return json({ error: 'Invalid webhook payload' }, { status: 400 }); }
}
