import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
import { expireUnpaidReservations } from '../lib/storeCheckout';
const STATUSES = new Set(['awaiting_payment', 'in_production', 'ready_for_pickup', 'shipped', 'delivered', 'cancelled']);
const FULFILLMENT = new Set(['unfulfilled', 'in_production', 'ready_for_pickup', 'shipped', 'delivered', 'cancelled']);
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function read(request: Request) { try { const data = await request.json(); return data && typeof data === 'object' && !Array.isArray(data) ? data as Record<string, unknown> : null; } catch { return null; } }
export async function handleProtectedStorefrontOrdersRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const label = path.match(/^\/api\/storefront\/orders\/([^/]+)\/items\/([^/]+)\/label-review$/); const order = path.match(/^\/api\/storefront\/orders(?:\/([^/]+))?$/); if (!label && !order) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db); const now = new Date().toISOString();
  if (label && request.method === 'PATCH') { const input = await read(request); const status = String(input?.label_approval_status ?? ''); const notes = String(input?.label_production_notes ?? '').trim(); if (!['pending_review', 'approved', 'changes_requested'].includes(status) || notes.length > 1_000) return json({ error: 'Invalid label review' }, { status: 400 }); const orderId = decodeURIComponent(label[1]).trim(); const itemId = decodeURIComponent(label[2]).trim(); const item = await repo.first<{ customization_json: string }>('SELECT customization_json FROM StoreOrderItem WHERE account_id = ? AND order_id = ? AND id = ?', [auth.accountId, orderId, itemId]); if (!item) return json({ error: 'Order item not found' }, { status: 404 }); let customization: Record<string, unknown> = {}; try { customization = JSON.parse(item.customization_json || '{}') as Record<string, unknown>; } catch { /* invalid legacy JSON */ } if (!Object.hasOwn(customization, 'label_approval_status')) return json({ error: 'This order item does not have a custom label.' }, { status: 400 }); const updated = { ...customization, label_approval_status: status, label_production_notes: notes }; await repo.run('UPDATE StoreOrderItem SET customization_json = ? WHERE account_id = ? AND order_id = ? AND id = ?', [JSON.stringify(updated), auth.accountId, orderId, itemId]); return json({ updated: true, customization: updated }); }
  const id = order?.[1] ? decodeURIComponent(order[1]).trim() : '';
  if (!id && request.method === 'GET') { await expireUnpaidReservations(repo, auth.accountId, now); const rows = await repo.all<Record<string, unknown>>(`SELECT o.id, o.order_number, o.customer_name, o.customer_email, o.customer_phone, o.status, o.payment_status, o.fulfillment_status, o.currency, o.subtotal_amount, o.discount_amount, o.shipping_amount, o.tax_amount, o.total_amount, o.tracking_number, o.staff_note, o.reservation_expires_at, o.paid_at, o.created_at, o.updated_at, COUNT(i.id) AS item_count FROM StoreOrder o LEFT JOIN StoreOrderItem i ON i.account_id = o.account_id AND i.order_id = o.id WHERE o.account_id = ? GROUP BY o.id ORDER BY o.created_at DESC`, [auth.accountId]); return json(rows.map((row) => ({ ...row, item_count: Number(row.item_count || 0) }))); }
  if (id && request.method === 'GET') { const found = await repo.first<Record<string, unknown>>('SELECT * FROM StoreOrder WHERE account_id = ? AND id = ?', [auth.accountId, id]); if (!found) return json({ error: 'Order not found' }, { status: 404 }); const [items, payments] = await Promise.all([repo.all<Record<string, unknown>>('SELECT id, product_id, product_name, product_image_data, unit_price, quantity, line_total, customization_json FROM StoreOrderItem WHERE account_id = ? AND order_id = ? ORDER BY created_at ASC', [auth.accountId, id]), repo.all<Record<string, unknown>>('SELECT id, provider, provider_payment_id, status, amount, currency, created_at, updated_at FROM StoreOrderPayment WHERE account_id = ? AND order_id = ? ORDER BY created_at ASC', [auth.accountId, id])]); return json({ ...found, items, payments }); }
  if (id && request.method === 'PATCH') { const input = await read(request); const existing = await repo.first<Record<string, unknown>>('SELECT * FROM StoreOrder WHERE account_id = ? AND id = ?', [auth.accountId, id]); if (!existing) return json({ error: 'Order not found' }, { status: 404 }); const requestedStatus = input?.status === undefined ? String(existing.status) : String(input.status); const fulfillment = input?.fulfillment_status === undefined ? String(existing.fulfillment_status) : String(input.fulfillment_status); const tracking = input?.tracking_number === undefined ? String(existing.tracking_number || '') : String(input.tracking_number).trim(); const note = input?.staff_note === undefined ? String(existing.staff_note || '') : String(input.staff_note).trim(); if (!STATUSES.has(requestedStatus) || !FULFILLMENT.has(fulfillment) || tracking.length > 500 || note.length > 4_000 || input?.payment_status !== undefined || requestedStatus === 'paid') return json({ error: 'Invalid order update' }, { status: 400 }); if (String(existing.payment_status) !== 'paid' && !['awaiting_payment', 'cancelled'].includes(requestedStatus)) return json({ error: 'An order must have verified payment before fulfillment.' }, { status: 409 }); if (String(existing.payment_status) !== 'paid' && input?.fulfillment_status !== undefined) return json({ error: 'An order must have verified payment before fulfillment.' }, { status: 409 }); if (String(existing.payment_status) === 'paid' && requestedStatus === 'cancelled') return json({ error: 'Paid orders must be refunded through the payment provider.' }, { status: 409 }); if (['cancelled', 'refunded'].includes(String(existing.status)) && (requestedStatus !== existing.status || input?.fulfillment_status !== undefined || input?.tracking_number !== undefined)) return json({ error: 'Cancelled or refunded orders cannot be reopened or updated.' }, { status: 409 }); await repo.run('UPDATE StoreOrder SET status = ?, fulfillment_status = ?, tracking_number = ?, staff_note = ?, updated_at = ? WHERE account_id = ? AND id = ?', [requestedStatus, fulfillment, tracking, note, now, auth.accountId, id]); return json((await repo.first<Record<string, unknown>>('SELECT * FROM StoreOrder WHERE account_id = ? AND id = ?', [auth.accountId, id]))!); }
  if (id && request.method === 'DELETE') { const cancelled = await repo.first<{ id: string }>("SELECT id FROM StoreOrder WHERE account_id = ? AND id = ? AND status = 'cancelled' LIMIT 1", [auth.accountId, id]); if (!cancelled) return json({ error: 'Only existing cancelled orders can be deleted.' }, { status: 409 }); await repo.run('DELETE FROM StoreOrder WHERE account_id = ? AND id = ?', [auth.accountId, id]); return json({ deleted: true }); }
  return null;
}
