import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
import { awardReward } from '../lib/rewards';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
export async function handleProtectedStorefrontModerationRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const review = path.match(/^\/api\/storefront\/reviews(?:\/([^/]+))?$/); const gallery = path.match(/^\/api\/storefront\/gallery(?:\/([^/]+))?$/); if (!review && !gallery) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db); const id = (review?.[1] || gallery?.[1]) ? decodeURIComponent((review?.[1] || gallery?.[1])!).trim() : '';
  if (review && !id && request.method === 'GET') return json((await repo.all<Record<string, unknown>>(`SELECT r.*, c.name AS customer_name, c.email AS customer_email, p.name AS product_name FROM StoreProductReview r JOIN StoreCustomer c ON c.account_id = r.account_id AND c.id = r.customer_id JOIN Product p ON p.account_id = r.account_id AND p.id = r.product_id WHERE r.account_id = ? ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END, r.created_at DESC`, [auth.accountId])).map((row) => ({ ...row, verified_purchase: Boolean(row.verified_purchase) })));
  if (gallery && !id && request.method === 'GET') return json(await repo.all<Record<string, unknown>>(`SELECT g.*, c.name AS customer_name, c.email AS customer_email FROM StoreCustomerGalleryItem g JOIN StoreCustomer c ON c.account_id = g.account_id AND c.id = g.customer_id WHERE g.account_id = ? ORDER BY CASE g.status WHEN 'pending' THEN 0 ELSE 1 END, g.updated_at DESC`, [auth.accountId]));
  const input = await body(request); const status = String(input?.status ?? ''); if (!id || request.method !== 'PATCH' || !['approved', 'rejected'].includes(status)) return json({ error: 'Invalid moderation request' }, { status: 400 }); const table = review ? 'StoreProductReview' : 'StoreCustomerGalleryItem'; const prior = review ? await repo.first<{ customer_id: string; verified_purchase: number; status: string }>('SELECT customer_id, verified_purchase, status FROM StoreProductReview WHERE account_id = ? AND id = ?', [auth.accountId, id]) : null; const result = await repo.run(`UPDATE ${table} SET status = ?, updated_at = ? WHERE account_id = ? AND id = ?`, [status, new Date().toISOString(), auth.accountId, id]); if (Number(result.meta.changes || 0) !== 1) return json({ error: review ? 'Review not found' : 'Gallery item not found' }, { status: 404 }); if (review && status === 'approved' && prior && prior.status !== 'approved') await awardReward(db, auth.accountId, prior.customer_id, prior.verified_purchase ? 25 : 10, 'review', id, prior.verified_purchase ? 'Verified review approved' : 'Review approved'); return json({ updated: true });
}
