import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function parseArray(value: unknown) { return Array.isArray(value) && value.length <= 500 && value.every((id) => typeof id === 'string' && id.trim() && id.length <= 120) ? [...new Set(value.map((id) => id.trim()))] : null; }
export async function handleProtectedStorefrontConfigRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db || new URL(request.url).pathname !== '/api/storefront') return null; const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db);
  if (request.method === 'GET') { const row = await repo.first<Record<string, unknown>>('SELECT store_slug, store_title, store_description, store_logo_data, store_banner_data, store_background_image_data, store_custom_html, store_preset_state, store_custom_full_mode, store_show_details, store_product_ids FROM Account WHERE id = ?', [auth.accountId]); if (!row) return json({ error: 'Account not found' }, { status: 404 }); let preset: unknown = null; let products: unknown[] = []; try { preset = row.store_preset_state ? JSON.parse(String(row.store_preset_state)) : null; } catch { /* legacy invalid JSON */ } try { products = JSON.parse(String(row.store_product_ids || '[]')); } catch { /* legacy invalid JSON */ } return json({ ...row, store_preset_state: preset, store_product_ids: Array.isArray(products) ? products : [], store_custom_full_mode: Boolean(row.store_custom_full_mode), store_show_details: Boolean(row.store_show_details) }); }
  if (request.method !== 'PUT') return null; let input: Record<string, unknown> | null = null; try { const value = await request.json(); input = value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { /* invalid */ } const text = (key: string, max: number) => typeof input?.[key] === 'string' && input[key].trim().length <= max ? input[key].trim() : null; const slug = text('store_slug', 100); const title = text('store_title', 180); const description = text('store_description', 4_000); const logo = text('store_logo_data', 2_500_000); const banner = text('store_banner_data', 2_500_000); const background = text('store_background_image_data', 2_500_000); const html = text('store_custom_html', 100_000); const products = parseArray(input?.store_product_ids); if (!input || !slug || !/^[a-z0-9-]+$/.test(slug) || title === null || description === null || logo === null || banner === null || background === null || html === null || products === null || typeof input.store_custom_full_mode !== 'boolean' || typeof input.store_show_details !== 'boolean') return json({ error: 'Invalid storefront configuration' }, { status: 400 }); const preset = input.store_preset_state === null ? '' : input.store_preset_state && typeof input.store_preset_state === 'object' ? JSON.stringify(input.store_preset_state) : null; if (preset === null || preset.length > 100_000) return json({ error: 'Invalid storefront preset state' }, { status: 400 }); const result = await repo.run('UPDATE Account SET store_slug = ?, store_title = ?, store_description = ?, store_logo_data = ?, store_banner_data = ?, store_background_image_data = ?, store_custom_html = ?, store_preset_state = ?, store_custom_full_mode = ?, store_show_details = ?, store_product_ids = ? WHERE id = ?', [slug, title, description, logo, banner, background, html, preset, input.store_custom_full_mode ? 1 : 0, input.store_show_details ? 1 : 0, JSON.stringify(products), auth.accountId]); return Number(result.meta.changes || 0) === 1 ? json({ updated: true }) : json({ error: 'Account not found' }, { status: 404 });
}
