import { randomBytes, scryptSync } from 'node:crypto';
import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function decode(value: string) { try { return decodeURIComponent(value).trim(); } catch { return ''; } }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function role(value: unknown) { return String(value || '').trim().toLowerCase().replace(/\s+/g, '_').slice(0, 40); }
function hash(value: string) { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(value, salt, 64).toString('hex')}`; }
function admin(roleName: string) { return ['owner', 'admin'].includes(roleName.toLowerCase()); }

export async function handleProtectedTeamAccessRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const match = path.match(/^\/api\/auth\/(users(?:\/([^/]+))?|join-requests(?:\/([^/]+)\/(approve|reject))?|join-code\/regenerate)$/); if (!match) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'teams_access_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db); const section = match[1]; const id = decode(match[2] || match[3] || ''); const action = match[4] || '';
  if (section === 'users' && request.method === 'GET') return json(await repo.all<Record<string, unknown>>('SELECT id, name, email, username, role, active, created_at, updated_at FROM AccountUser WHERE account_id = ? ORDER BY created_at ASC', [auth.accountId]));
  if (section === 'users' && request.method === 'POST') { if (!admin(auth.role)) return json({ error: 'Forbidden' }, { status: 403 }); const input = await body(request); const name = String(input?.name || '').trim(); const email = String(input?.email || '').trim().toLowerCase(); const pass = String(input?.password || ''); const requestedRole = role(input?.role || 'member'); if (name.length < 2 || name.length > 120 || !EMAIL.test(email) || pass.length < 6 || pass.length > 200 || !requestedRole) return json({ error: 'Invalid user' }, { status: 400 }); const exists = await repo.first<{ id: string }>('SELECT id FROM AccountUser WHERE account_id = ? AND (lower(username) = ? OR lower(email) = ?) LIMIT 1', [auth.accountId, email, email]); if (exists) return json({ error: 'Username already exists in this account' }, { status: 409 }); const now = new Date().toISOString(); const userId = crypto.randomUUID(); await repo.run('INSERT INTO AccountUser (id, account_id, name, email, username, password_hash, role, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)', [userId, auth.accountId, name, email, email, hash(pass), requestedRole, now, now]); return json((await repo.first<Record<string, unknown>>('SELECT id, name, email, username, role, active, created_at, updated_at FROM AccountUser WHERE id = ? AND account_id = ?', [userId, auth.accountId]))!, { status: 201 }); }
  if (section.startsWith('users/') && id && request.method === 'DELETE') { if (!admin(auth.role)) return json({ error: 'Forbidden' }, { status: 403 }); if (id === auth.userId) return json({ error: 'Cannot delete your own account' }, { status: 400 }); const user = await repo.first<{ id: string }>('SELECT id FROM AccountUser WHERE id = ? AND account_id = ?', [id, auth.accountId]); if (!user) return json({ error: 'User not found' }, { status: 404 }); await repo.batch([{ query: 'DELETE FROM AuthSession WHERE account_user_id = ?', values: [id] }, { query: 'DELETE FROM AccountUser WHERE id = ? AND account_id = ?', values: [id, auth.accountId] }]); return new Response(null, { status: 204 }); }
  if (section === 'join-code/regenerate' && request.method === 'POST') { if (!admin(auth.role)) return json({ error: 'Forbidden' }, { status: 403 }); const code = randomBytes(4).toString('hex').toUpperCase(); await repo.run('UPDATE Account SET join_code = ? WHERE id = ?', [code, auth.accountId]); return json({ join_code: code }); }
  if (section === 'join-requests' && request.method === 'GET') { if (!admin(auth.role)) return json({ error: 'Forbidden' }, { status: 403 }); return json(await repo.all<Record<string, unknown>>('SELECT id, account_id, name, email, username, requested_role, status, created_at, updated_at FROM AccountJoinRequest WHERE account_id = ? ORDER BY created_at DESC', [auth.accountId])); }
  if (section.startsWith('join-requests/') && id && ['approve', 'reject'].includes(action) && request.method === 'POST') { if (!admin(auth.role)) return json({ error: 'Forbidden' }, { status: 403 }); const requestRow = await repo.first<Record<string, unknown>>("SELECT * FROM AccountJoinRequest WHERE id = ? AND account_id = ? AND status = 'pending' LIMIT 1", [id, auth.accountId]); if (!requestRow) return json({ error: 'Pending join request not found' }, { status: 404 }); const now = new Date().toISOString(); if (action === 'approve') { const exists = await repo.first<{ id: string }>('SELECT id FROM AccountUser WHERE account_id = ? AND (lower(username) = ? OR lower(email) = ?) LIMIT 1', [auth.accountId, String(requestRow.username).toLowerCase(), String(requestRow.email).toLowerCase()]); if (exists) return json({ error: 'Username already exists in this account' }, { status: 409 }); await repo.batch([{ query: 'INSERT INTO AccountUser (id, account_id, name, email, username, password_hash, role, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)', values: [crypto.randomUUID(), auth.accountId, String(requestRow.name), String(requestRow.email), String(requestRow.username), String(requestRow.password_hash), role(requestRow.requested_role) || 'member', now, now] }, { query: "UPDATE AccountJoinRequest SET status = 'approved', reviewed_by_user_id = ?, updated_at = ? WHERE id = ? AND account_id = ?", values: [auth.userId, now, id, auth.accountId] }]); } else await repo.run("UPDATE AccountJoinRequest SET status = 'rejected', reviewed_by_user_id = ?, updated_at = ? WHERE id = ? AND account_id = ? AND status = 'pending'", [auth.userId, now, id, auth.accountId]); return new Response(null, { status: 204 }); }
  return null;
}
