import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';

const FEATURES = ['products', 'products_edit', 'supplies', 'supplies_edit', 'recipes', 'recipes_edit', 'calculators', 'calculators_edit', 'batches', 'batches_edit', 'labels', 'labels_edit', 'storefront', 'storefront_edit', 'teams', 'teams_access', 'teams_access_edit', 'teams_employees', 'teams_employees_edit', 'teams_roles', 'teams_roles_edit', 'teams_contacts', 'teams_contacts_edit'];
const BUILT_IN = new Set(['owner', 'admin', 'member']);
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function role(value: string) { return value.trim().toLowerCase().replace(/\s+/g, '_').slice(0, 40); }
function decode(value: string) { try { return decodeURIComponent(value); } catch { return ''; } }
async function input(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
async function permissions(repo: ReturnType<typeof createD1Repository>, accountId: string, roleName: string) { const rows = await repo.all<{ feature_key: string; enabled: number }>('SELECT feature_key, enabled FROM AccountRolePermission WHERE account_id = ? AND role_name = ?', [accountId, roleName]); const defaults = Object.fromEntries(FEATURES.map((key) => [key, true])); if (!rows.length) return BUILT_IN.has(roleName) ? defaults : Object.fromEntries(FEATURES.map((key) => [key, false])); for (const row of rows) if (FEATURES.includes(row.feature_key)) defaults[row.feature_key] = Boolean(row.enabled); return defaults; }

export async function handleProtectedTeamRolesRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const match = path.match(/^\/api\/auth\/(permissions|roles(?:\/([^/]+)(?:\/permissions)?)?)$/); if (!match) return null; const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); const repo = createD1Repository(db); const route = match[1]; const roleName = role(decode(match[2] || ''));
  if (route === 'permissions' && request.method === 'GET') return json({ role: role(auth.role), permissions: await permissions(repo, auth.accountId, role(auth.role)) });
  if (!await canEditFeature(db, auth, 'teams_roles_edit') || !['owner', 'admin'].includes(role(auth.role))) return json({ error: 'Forbidden' }, { status: 403 });
  if (route === 'roles' && request.method === 'GET') { const custom = await repo.all<{ name: string }>('SELECT name FROM AccountRole WHERE account_id = ? ORDER BY name', [auth.accountId]); const names = [...new Set(['owner', 'admin', 'member', ...custom.map((row) => row.name)])]; return json(await Promise.all(names.map(async (name) => ({ name, built_in: BUILT_IN.has(name), permissions: await permissions(repo, auth.accountId, name) })))); }
  if (route === 'roles' && request.method === 'POST') { const data = await input(request); const name = role(String(data?.name || '')); if (name.length < 2 || BUILT_IN.has(name)) return json({ error: BUILT_IN.has(name) ? 'Role name is reserved' : 'Invalid role name' }, { status: 400 }); const now = new Date().toISOString(); const existing = await repo.first<{ id: string }>('SELECT id FROM AccountRole WHERE account_id = ? AND name = ?', [auth.accountId, name]); if (existing) return json({ error: 'Role already exists' }, { status: 409 }); await repo.batch([{ query: 'INSERT INTO AccountRole (id, account_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)', values: [crypto.randomUUID(), auth.accountId, name, now, now] }, ...FEATURES.map((feature) => ({ query: 'INSERT INTO AccountRolePermission (id, account_id, role_name, feature_key, enabled, created_at, updated_at) VALUES (?, ?, ?, ?, 1, ?, ?)', values: [crypto.randomUUID(), auth.accountId, name, feature, now, now] }))]); return json({ name, created_at: now, updated_at: now }, { status: 201 }); }
  if (route.startsWith('roles/') && roleName && request.method === 'PUT' && path.endsWith('/permissions')) { const exists = BUILT_IN.has(roleName) || await repo.first<{ id: string }>('SELECT id FROM AccountRole WHERE account_id = ? AND name = ?', [auth.accountId, roleName]); if (!exists) return json({ error: 'Role not found' }, { status: 404 }); const data = await input(request); const map = data?.permissions; if (!map || typeof map !== 'object' || Array.isArray(map)) return json({ error: 'Invalid permissions' }, { status: 400 }); const now = new Date().toISOString(); await repo.batch([{ query: 'DELETE FROM AccountRolePermission WHERE account_id = ? AND role_name = ?', values: [auth.accountId, roleName] }, ...FEATURES.map((feature) => ({ query: 'INSERT INTO AccountRolePermission (id, account_id, role_name, feature_key, enabled, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)', values: [crypto.randomUUID(), auth.accountId, roleName, feature, Boolean((map as Record<string, unknown>)[feature]) ? 1 : 0, now, now] }))]); return json({ ok: true }); }
  if (route.startsWith('roles/') && roleName && request.method === 'DELETE') { if (BUILT_IN.has(roleName)) return json({ error: 'Built-in role cannot be deleted' }, { status: 400 }); const used = await repo.first<{ id: string }>('SELECT id FROM AccountUser WHERE account_id = ? AND lower(role) = ? LIMIT 1', [auth.accountId, roleName]); if (used) return json({ error: 'Role is assigned to one or more users' }, { status: 400 }); await repo.batch([{ query: 'DELETE FROM AccountRolePermission WHERE account_id = ? AND role_name = ?', values: [auth.accountId, roleName] }, { query: 'DELETE FROM AccountRole WHERE account_id = ? AND name = ?', values: [auth.accountId, roleName] }]); return new Response(null, { status: 204 }); }
  return null;
}
