import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function email(value: unknown) { const out = String(value ?? '').trim().toLowerCase(); return out.length <= 320 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out) ? out : null; }
function money(value: unknown) { const amount = Number(value); return Number.isFinite(amount) && amount > 0 && amount <= 5_000 ? Math.round(amount * 100) / 100 : null; }
async function notice(repo: ReturnType<typeof createD1Repository>, accountId: string, customerId: string, category: string, title: string, message: string) { await repo.run('INSERT INTO StoreCustomerNotification (id, account_id, customer_id, category, title, message, is_read, created_at) VALUES (?, ?, ?, ?, ?, ?, 0, ?)', [crypto.randomUUID(), accountId, customerId, category, title, message, new Date().toISOString()]); }
export async function handleProtectedStorefrontBalancesRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const adjust = path.match(/^\/api\/storefront\/gift-cards\/([^/]+)\/adjust$/); const credits = path === '/api/storefront/gift-cards/credits'; const cards = path === '/api/storefront/gift-cards'; if (!adjust && !credits && !cards) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db);
  if (cards && request.method === 'GET') { const [giftCards, usages, customerCredits] = await Promise.all([repo.all<Record<string, unknown>>(`SELECT g.*, c.name AS customer_name, c.email AS customer_email FROM StoreGiftCard g LEFT JOIN StoreCustomer c ON c.account_id = g.account_id AND c.id = g.customer_id WHERE g.account_id = ? ORDER BY g.updated_at DESC`, [auth.accountId]), repo.all<Record<string, unknown>>(`SELECT u.*, g.code AS gift_card_code FROM StoreGiftCardUsage u JOIN StoreGiftCard g ON g.account_id = u.account_id AND g.id = u.gift_card_id WHERE u.account_id = ? ORDER BY u.created_at DESC LIMIT 250`, [auth.accountId]), repo.all<Record<string, unknown>>(`SELECT cr.*, c.name AS customer_name, c.email AS customer_email FROM StoreCustomerCredit cr JOIN StoreCustomer c ON c.account_id = cr.account_id AND c.id = cr.customer_id WHERE cr.account_id = ? ORDER BY cr.updated_at DESC`, [auth.accountId])]); return json({ cards: giftCards.map((row) => ({ ...row, active: Boolean(row.active) })), usages, credits: customerCredits.map((row) => ({ ...row, active: Boolean(row.active) })) }); }
  const input = await body(request);
  if (cards && request.method === 'POST') { const customerEmail = email(input?.customer_email); const amount = money(input?.amount); const customCode = String(input?.code ?? '').trim().toUpperCase(); const note = String(input?.note ?? '').trim(); if (!customerEmail || amount === null || customCode.length > 80 || note.length > 500) return json({ error: 'Invalid gift card data' }, { status: 400 }); const customer = await repo.first<{ id: string }>('SELECT id FROM StoreCustomer WHERE account_id = ? AND lower(email) = ? AND active = 1 LIMIT 1', [auth.accountId, customerEmail]); if (!customer) return json({ error: 'Create or locate the customer storefront account before issuing a gift card.' }, { status: 404 }); const code = customCode || `CM-GIFT-${crypto.randomUUID().replaceAll('-', '').slice(0, 10).toUpperCase()}`; const id = crypto.randomUUID(); const now = new Date().toISOString(); await repo.batch([{ query: 'INSERT INTO StoreGiftCard (id, account_id, code, customer_id, initial_balance, balance, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)', values: [id, auth.accountId, code, customer.id, amount, amount, now, now] }, { query: 'INSERT INTO StoreGiftCardUsage (id, account_id, gift_card_id, amount, balance_after, usage_type, note, created_at) VALUES (?, ?, ?, ?, ?, \'issue\', ?, ?)', values: [crypto.randomUUID(), auth.accountId, id, amount, amount, note || 'Gift card issued by staff.', now] }]); await notice(repo, auth.accountId, customer.id, 'gift_card', 'Gift card added', `A gift card ending in ${code.slice(-6)} with a $${amount.toFixed(2)} balance was added to your account.`); return json({ id, code }, { status: 201 }); }
  if (adjust && request.method === 'POST') { const amount = money(input?.amount); const note = String(input?.note ?? '').trim(); if (amount === null || note.length < 2 || note.length > 500 || (input?.active !== undefined && typeof input.active !== 'boolean')) return json({ error: 'Invalid gift card adjustment' }, { status: 400 }); const id = decodeURIComponent(adjust[1]).trim(); const card = await repo.first<{ customer_id: string; code: string; balance: number; active: number }>('SELECT customer_id, code, balance, active FROM StoreGiftCard WHERE account_id = ? AND id = ?', [auth.accountId, id]); if (!card) return json({ error: 'Gift card not found' }, { status: 404 }); const balance = Math.round((Number(card.balance) + amount) * 100) / 100; const active = input?.active === undefined ? card.active : input.active ? 1 : 0; const now = new Date().toISOString(); await repo.batch([{ query: 'UPDATE StoreGiftCard SET balance = ?, active = ?, updated_at = ? WHERE account_id = ? AND id = ?', values: [balance, active, now, auth.accountId, id] }, { query: 'INSERT INTO StoreGiftCardUsage (id, account_id, gift_card_id, amount, balance_after, usage_type, note, created_at) VALUES (?, ?, ?, ?, ?, \'staff_adjustment\', ?, ?)', values: [crypto.randomUUID(), auth.accountId, id, amount, balance, note, now] }]); if (card.customer_id) await notice(repo, auth.accountId, card.customer_id, 'gift_card', 'Gift card updated', `Staff added $${amount.toFixed(2)} to your gift card ending in ${card.code.slice(-6)}. New balance: $${balance.toFixed(2)}. ${note}`); return json({ updated: true }); }
  if (credits && request.method === 'POST') { const customerEmail = email(input?.customer_email); const amount = money(input?.amount); const type = String(input?.credit_type ?? ''); const label = String(input?.label ?? '').trim(); if (!customerEmail || amount === null || !['free_gift', 'giveaway_balance'].includes(type) || label.length < 2 || label.length > 160) return json({ error: 'Invalid account credit' }, { status: 400 }); const customer = await repo.first<{ id: string }>('SELECT id FROM StoreCustomer WHERE account_id = ? AND lower(email) = ? AND active = 1 LIMIT 1', [auth.accountId, customerEmail]); if (!customer) return json({ error: 'Customer storefront account not found.' }, { status: 404 }); const id = crypto.randomUUID(); const now = new Date().toISOString(); await repo.run('INSERT INTO StoreCustomerCredit (id, account_id, customer_id, credit_type, label, balance, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)', [id, auth.accountId, customer.id, type, label, amount, now, now]); await notice(repo, auth.accountId, customer.id, type, type === 'free_gift' ? 'Free gift added' : 'Giveaway balance added', `${label}: $${amount.toFixed(2)} was added to your storefront account.`); return json({ id }, { status: 201 }); }
  return null;
}
