import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function read(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function number(value: unknown, min: number, max: number, integer = false) { const result = Number(value); return Number.isFinite(result) && result >= min && result <= max && (!integer || Number.isInteger(result)) ? result : null; }
function iso(value: unknown) { if (value === null) return null; if (typeof value !== 'string' || !value.trim() || Number.isNaN(Date.parse(value))) return undefined; return value.trim(); }
function row(value: Record<string, unknown>) { return { ...value, active: Boolean(value.active), stack_with_mix: Boolean(value.stack_with_mix), stack_with_gift_card: Boolean(value.stack_with_gift_card) }; }
export async function handleProtectedStorefrontDiscountsRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const match = new URL(request.url).pathname.match(/^\/api\/storefront\/discount-codes(?:\/([^/]+))?$/); if (!match) return null; const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); const repo = createD1Repository(db); const id = match[1] ? decodeURIComponent(match[1]).trim() : '';
  if (!id && request.method === 'GET') { const [codes, redemptions] = await Promise.all([repo.all<Record<string, unknown>>('SELECT * FROM StoreDiscountCode WHERE account_id = ? ORDER BY created_at DESC', [auth.accountId]), repo.all<Record<string, unknown>>(`SELECT r.*, c.code, o.order_number, o.customer_email FROM StoreDiscountRedemption r JOIN StoreDiscountCode c ON c.account_id = r.account_id AND c.id = r.discount_code_id JOIN StoreOrder o ON o.account_id = r.account_id AND o.id = r.order_id WHERE r.account_id = ? ORDER BY r.created_at DESC LIMIT 250`, [auth.accountId])]); return json({ codes: codes.map(row), redemptions }); }
  const body = await read(request);
  if (!id && request.method === 'POST') { const code = String(body?.code ?? '').trim().toUpperCase(); const type = String(body?.discount_type ?? ''); const value = number(body?.discount_value, 0.01, 10_000); const minimum = number(body?.minimum_subtotal, 0, 100_000); const starts = body?.starts_at === undefined ? null : iso(body.starts_at); const expires = body?.expires_at === undefined ? null : iso(body.expires_at); const usage = number(body?.usage_limit, 0, 100_000, true); const perCustomer = number(body?.per_customer_limit, 0, 100_000, true); if (!body || !/^[A-Z0-9_-]{2,80}$/.test(code) || !['percent', 'fixed'].includes(type) || value === null || minimum === null || starts === undefined || expires === undefined || usage === null || perCustomer === null || typeof body.stack_with_mix !== 'boolean' || typeof body.stack_with_gift_card !== 'boolean' || typeof body.active !== 'boolean' || (type === 'percent' && value > 100) || (starts && expires && starts >= expires)) return json({ error: 'Invalid discount code' }, { status: 400 }); const id = crypto.randomUUID(); const now = new Date().toISOString(); await repo.run(`INSERT INTO StoreDiscountCode (id, account_id, code, discount_type, discount_value, minimum_subtotal, starts_at, expires_at, usage_limit, per_customer_limit, stack_with_mix, stack_with_gift_card, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [id, auth.accountId, code, type, value, minimum, starts, expires, usage, perCustomer, body.stack_with_mix ? 1 : 0, body.stack_with_gift_card ? 1 : 0, body.active ? 1 : 0, now, now]); const created = await repo.first<Record<string, unknown>>('SELECT * FROM StoreDiscountCode WHERE account_id = ? AND id = ?', [auth.accountId, id]); return json(row(created!), { status: 201 }); }
  if (id && request.method === 'PATCH') { const current = await repo.first<Record<string, unknown>>('SELECT * FROM StoreDiscountCode WHERE account_id = ? AND id = ?', [auth.accountId, id]); if (!current) return json({ error: 'Discount code not found' }, { status: 404 }); const active = body?.active === undefined ? Number(current.active) : typeof body.active === 'boolean' ? body.active ? 1 : 0 : null; const expires = body?.expires_at === undefined ? current.expires_at as string | null : iso(body.expires_at); const usage = body?.usage_limit === undefined ? Number(current.usage_limit) : number(body.usage_limit, 0, 100_000, true); const perCustomer = body?.per_customer_limit === undefined ? Number(current.per_customer_limit) : number(body.per_customer_limit, 0, 100_000, true); if (!body || active === null || expires === undefined || usage === null || perCustomer === null) return json({ error: 'Invalid discount code update' }, { status: 400 }); await repo.run('UPDATE StoreDiscountCode SET active = ?, expires_at = ?, usage_limit = ?, per_customer_limit = ?, updated_at = ? WHERE account_id = ? AND id = ?', [active, expires, usage, perCustomer, new Date().toISOString(), auth.accountId, id]); return json(row((await repo.first<Record<string, unknown>>('SELECT * FROM StoreDiscountCode WHERE account_id = ? AND id = ?', [auth.accountId, id]))!)); }
  return null;
}
