import { randomBytes } from 'node:crypto';
import { createD1Repository } from '../lib/d1';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function segment(value: string) { try { return decodeURIComponent(value).trim(); } catch { return ''; } }
function value(input: Record<string, unknown> | null, key: string, minimum: number, maximum: number) { const result = String(input?.[key] || '').trim(); return result.length >= minimum && result.length <= maximum ? result : ''; }
function ip(request: Request) { return String(request.headers.get('cf-connecting-ip') || '').slice(0, 120); }

export async function handlePublicAppealsRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const url = new URL(request.url); const match = url.pathname.match(/^\/api\/appeals(?:\/([^/]+)(?:\/(messages|auto-login))?)?$/); if (!match) return null; const repo = createD1Repository(db); const id = segment(match[1] || ''); const action = match[2] || ''; const key = url.searchParams.get('key') || '';
  if (!id && request.method === 'POST') { const input = await body(request); const identifier = value(input, 'account_identifier', 2, 254); const name = value(input, 'name', 2, 120); const reason = value(input, 'reason', 2, 500); const details = value(input, 'details', 2, 5000); const email = value(input, 'email', 0, 254); if (!identifier || !name || !reason || !details || (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) return json({ error: 'Invalid appeal' }, { status: 400 }); const account = await repo.first<{ id: string }>('SELECT id FROM Account WHERE lower(name) = ? OR lower(store_slug) = ? LIMIT 1', [identifier.toLowerCase(), identifier.toLowerCase()]); const ticketId = crypto.randomUUID(); const participantKey = randomBytes(24).toString('hex'); const now = new Date().toISOString(); await repo.batch([{ query: "INSERT INTO BanAppealTicket (id, account_id, account_identifier, email, name, reason, details, participant_key, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'open', ?, ?)", values: [ticketId, account?.id || null, identifier, email, name, reason, details, participantKey, now, now] }, { query: "INSERT INTO BanAppealMessage (id, ticket_id, sender_type, sender_name, message, created_at) VALUES (?, ?, 'user', ?, ?, ?)", values: [crypto.randomUUID(), ticketId, name, `Appeal reason: ${reason}\n${details}`, now] }]); return json({ ok: true, ticket_id: ticketId, access_key: participantKey }, { status: 201 }); }
  if (id === 'open' && request.method === 'GET') { const identifier = String(url.searchParams.get('identifier') || '').trim().toLowerCase(); if (!identifier) return json({ error: 'Identifier is required' }, { status: 400 }); const ticket = await repo.first<{ id: string; participant_key: string; status: string }>("SELECT id, participant_key, status FROM BanAppealTicket WHERE lower(account_identifier) = ? AND status IN ('open', 'in_review') ORDER BY updated_at DESC, created_at DESC LIMIT 1", [identifier]); return ticket ? json({ exists: true, ticket_id: ticket.id, access_key: ticket.participant_key, status: ticket.status }) : json({ exists: false }); }
  if (!id || !key) return id ? json({ error: 'Appeal access key is required' }, { status: 401 }) : null;
  if (!action && request.method === 'GET') { const ticket = await repo.first<Record<string, unknown>>('SELECT id, account_identifier, email, name, reason, details, status, created_at FROM BanAppealTicket WHERE id = ? AND participant_key = ? LIMIT 1', [id, key]); if (!ticket) return json({ error: 'Appeal ticket not found' }, { status: 404 }); return json({ ticket, messages: await repo.all<Record<string, unknown>>('SELECT id, sender_type, sender_name, message, created_at FROM BanAppealMessage WHERE ticket_id = ? ORDER BY created_at', [id]) }); }
  if (action === 'messages' && request.method === 'POST') { const ticket = await repo.first<{ name: string; status: string }>('SELECT name, status FROM BanAppealTicket WHERE id = ? AND participant_key = ? LIMIT 1', [id, key]); const message = value(await body(request), 'message', 1, 5000); if (!ticket) return json({ error: 'Appeal ticket not found' }, { status: 404 }); if (['resolved', 'rejected'].includes(ticket.status)) return json({ error: 'This appeal is closed' }, { status: 400 }); if (!message) return json({ error: 'Invalid message' }, { status: 400 }); const now = new Date().toISOString(); const messageId = crypto.randomUUID(); await repo.batch([{ query: "INSERT INTO BanAppealMessage (id, ticket_id, sender_type, sender_name, message, created_at) VALUES (?, ?, 'user', ?, ?, ?)", values: [messageId, id, ticket.name || 'User', message, now] }, { query: 'UPDATE BanAppealTicket SET updated_at = ? WHERE id = ?', values: [now, id] }]); return json({ ok: true, id: messageId, created_at: now }, { status: 201 }); }
  if (action === 'auto-login' && request.method === 'POST') { const ticket = await repo.first<{ account_id: string | null; account_identifier: string; status: string }>('SELECT account_id, account_identifier, status FROM BanAppealTicket WHERE id = ? AND participant_key = ? LIMIT 1', [id, key]); if (!ticket) return json({ error: 'Appeal ticket not found' }, { status: 404 }); if (ticket.status !== 'resolved') return json({ error: 'Appeal is not resolved yet' }, { status: 400 }); const account = ticket.account_id ? await repo.first<Record<string, unknown>>('SELECT id, name, join_code, plan_tier, is_banned, access_disabled FROM Account WHERE id = ? LIMIT 1', [ticket.account_id]) : await repo.first<Record<string, unknown>>('SELECT id, name, join_code, plan_tier, is_banned, access_disabled FROM Account WHERE lower(name) = ? OR lower(store_slug) = ? LIMIT 1', [ticket.account_identifier.toLowerCase(), ticket.account_identifier.toLowerCase()]); if (!account) return json({ error: 'Account not found' }, { status: 404 }); if (Number(account.is_banned) || Number(account.access_disabled)) return json({ error: 'Account is still blocked' }, { status: 403 }); const user = await repo.first<Record<string, unknown>>("SELECT id, name, email, username, role FROM AccountUser WHERE account_id = ? AND active = 1 ORDER BY CASE WHEN role = 'owner' THEN 0 ELSE 1 END, created_at LIMIT 1", [account.id]); if (!user) return json({ error: 'No active user found for account' }, { status: 404 }); const token = randomBytes(32).toString('hex'); const now = new Date().toISOString(); const expiresAt = new Date(Date.now() + 30 * 86400000).toISOString(); await repo.batch([{ query: 'INSERT INTO AuthSession (id, account_user_id, token, expires_at, created_at) VALUES (?, ?, ?, ?, ?)', values: [crypto.randomUUID(), user.id, token, expiresAt, now] }, { query: "INSERT INTO AuthEvent (id, account_id, account_user_id, email, event_type, ip_address, created_at) VALUES (?, ?, ?, ?, 'appeal_auto_login', ?, ?)", values: [crypto.randomUUID(), account.id, user.id, String(user.email || ''), ip(request), now] }]); return json({ token, user: { user_id: user.id, account_id: account.id, account_name: account.name, plan_tier: account.plan_tier || 'free', join_code: account.join_code || '', username: user.name || user.username, email: user.email || '', role: user.role, expires_at: expiresAt } }); }
  return null;
}
