import { createD1Repository } from '../lib/d1';
import { createCustomerSessionToken, hashCustomerPassword, resolveStoreCustomer, verifyCustomerPassword } from '../lib/customerAuth';
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function profile(row: Record<string, unknown>, expiresAt: string) { return { id: row.customerId || row.id, name: row.name, email: row.email, phone: row.phone || '', marketing_opt_in: Boolean(row.marketingOptIn ?? row.marketing_opt_in), reminder_opt_in: Boolean(row.reminderOptIn ?? row.reminder_opt_in), birthday: row.birthday || '', anniversary: row.anniversary || '', occasion_reminder_opt_in: Boolean(row.occasionReminderOptIn ?? row.occasion_reminder_opt_in), expires_at: expiresAt }; }
export async function handlePublicCustomerAuthRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const match = new URL(request.url).pathname.match(/^\/api\/public\/store\/([^/]+)\/customers\/(register|login|me)$/); if (!match) return null; let slug = ''; try { slug = decodeURIComponent(match[1]).trim(); } catch { /* invalid */ } if (!slug) return json({ error: 'Invalid store slug' }, { status: 400 }); const route = match[2]; const repo = createD1Repository(db); const account = await repo.first<{ id: string }>("SELECT id FROM Account WHERE lower(store_slug) = ? AND plan_tier = 'elite' LIMIT 1", [slug.toLowerCase()]); if (!account) return json({ error: 'Storefront not found' }, { status: 404 });
  if (route === 'me' && request.method === 'GET') { const customer = await resolveStoreCustomer(db, request, slug); if (!customer) return json({ error: 'Unauthorized' }, { status: 401 }); const addresses = await repo.all<Record<string, unknown>>('SELECT id, label, recipient_name, street_address_1, street_address_2, city, state_region, postal_code, country, phone, is_default FROM StoreCustomerAddress WHERE account_id = ? AND customer_id = ? ORDER BY is_default DESC, created_at DESC', [customer.accountId, customer.customerId]); return json({ customer: profile(customer, customer.expiresAt), addresses: addresses.map((address) => ({ ...address, is_default: Boolean(address.is_default) })) }); }
  if (!['register', 'login'].includes(route) || request.method !== 'POST') return null; let input: Record<string, unknown> | null = null; try { const value = await request.json(); input = value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { /* invalid */ } const email = String(input?.email ?? '').trim().toLowerCase(); const password = String(input?.password ?? ''); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email.length > 254 || password.length < 8 || password.length > 200) return json({ error: 'Invalid email or password' }, { status: 400 }); const now = new Date().toISOString(); const expiresAt = new Date(Date.now() + 30 * 86400000).toISOString();
  if (route === 'register') { const name = String(input?.name ?? '').trim(); if (name.length < 1 || name.length > 120 || password !== String(input?.password_confirm ?? '')) return json({ error: 'Invalid registration data' }, { status: 400 }); const exists = await repo.first<{ id: string }>('SELECT id FROM StoreCustomer WHERE account_id = ? AND lower(email) = ? LIMIT 1', [account.id, email]); if (exists) return json({ error: 'An account with this email already exists for this store' }, { status: 409 }); const id = crypto.randomUUID(); const token = createCustomerSessionToken(); await repo.batch([{ query: 'INSERT INTO StoreCustomer (id, account_id, name, email, password_hash, phone, marketing_opt_in, reminder_opt_in, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, \'\', 0, 0, 1, ?, ?)', values: [id, account.id, name, email, hashCustomerPassword(password), now, now] }, { query: 'INSERT INTO StoreCustomerSession (id, account_id, customer_id, token, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?)', values: [crypto.randomUUID(), account.id, id, token, expiresAt, now] }]); return json({ token, customer: profile({ id, name, email, phone: '' }, expiresAt) }, { status: 201 }); }
  const customer = await repo.first<Record<string, unknown>>('SELECT id, name, email, phone, marketing_opt_in, reminder_opt_in, birthday, anniversary, occasion_reminder_opt_in, password_hash, active FROM StoreCustomer WHERE account_id = ? AND lower(email) = ? LIMIT 1', [account.id, email]); if (!customer || Number(customer.active) !== 1 || !verifyCustomerPassword(password, String(customer.password_hash))) return json({ error: 'Invalid email or password' }, { status: 401 }); const token = createCustomerSessionToken(); await repo.run('INSERT INTO StoreCustomerSession (id, account_id, customer_id, token, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), account.id, customer.id, token, expiresAt, now]); return json({ token, customer: profile(customer, expiresAt) });
}
