import { resolveStoreCustomer } from '../lib/customerAuth';
import { createD1Repository } from '../lib/d1';

function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function string(value: unknown, min: number, max: number) { const output = String(value ?? '').trim(); return output.length >= min && output.length <= max ? output : null; }
function published(raw: unknown, id: string) { try { const values = JSON.parse(String(raw || '[]')); return Array.isArray(values) && values.map(String).includes(id); } catch { return false; } }
function jsonItems(value: unknown, size: number) {
  if (!Array.isArray(value) || value.length !== size || ![3, 4, 6, 12].includes(size)) return null;
  const valid = value.every((item) => item && typeof item === 'object' && string((item as Record<string, unknown>).name, 1, 160) && ['4 oz', '8 oz', '10 oz', '16 oz'].includes(String((item as Record<string, unknown>).size)) && ['1 wick', '2 wicks', '3 wicks'].includes(String((item as Record<string, unknown>).wickCount)) && ['Cotton wick', 'Wood wick'].includes(String((item as Record<string, unknown>).wickType)));
  return valid ? JSON.stringify(value) : null;
}
async function store(repo: ReturnType<typeof createD1Repository>, slug: string) { return repo.first<{ id: string; store_product_ids: string }>("SELECT id, store_product_ids FROM Account WHERE lower(store_slug) = ? AND plan_tier = 'elite' LIMIT 1", [slug.toLowerCase()]); }

export async function handlePublicCustomerEngagementRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname;
  const match = path.match(/^\/api\/public\/store\/([^/]+)\/customers\/(collections|favorites|registries|gallery|reviews)(?:\/([^/]+))?$/);
  if (!match) return null; let slug = ''; try { slug = decodeURIComponent(match[1]).trim(); } catch { /* invalid */ } if (!slug) return json({ error: 'Invalid store slug' }, { status: 400 });
  const customer = await resolveStoreCustomer(db, request, slug); if (!customer) return json({ error: 'Unauthorized' }, { status: 401 }); const repo = createD1Repository(db); const area = match[2]; const id = match[3] ? decodeURIComponent(match[3]).trim() : ''; const account = await store(repo, slug); if (!account || account.id !== customer.accountId) return json({ error: 'Storefront not found' }, { status: 404 }); const now = new Date().toISOString();

  if (area === 'collections' && request.method === 'GET') { const rows = await repo.all<Record<string, unknown>>('SELECT id, collection_name, label_text, collection_size, items_json, created_at, updated_at FROM StoreCustomerCollection WHERE account_id = ? AND customer_id = ? ORDER BY updated_at DESC', [customer.accountId, customer.customerId]); return json(rows.map((row) => { let items: unknown[] = []; try { const parsed = JSON.parse(String(row.items_json || '[]')); items = Array.isArray(parsed) ? parsed : []; } catch { /* invalid legacy JSON */ } return { ...row, collection_size: Number(row.collection_size), items }; })); }
  if (area === 'collections' && request.method === 'POST') { const input = await body(request); const collectionName = string(input?.collection_name, 1, 120); const label = string(input?.label_text, 0, 160); const size = Number(input?.collection_size); const items = jsonItems(input?.items, size); if (!collectionName || label === null || !items) return json({ error: 'Select the exact number of valid candles for this collection.' }, { status: 400 }); await repo.run('INSERT INTO StoreCustomerCollection (id, account_id, customer_id, collection_name, label_text, collection_size, items_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), customer.accountId, customer.customerId, collectionName, label, size, items, now, now]); return json({ saved: true }, { status: 201 }); }

  if (area === 'favorites' && request.method === 'GET') return json(await repo.all<Record<string, unknown>>('SELECT p.id, p.name, p.image_data, p.price, f.created_at FROM StoreCustomerFavorite f JOIN Product p ON p.account_id = f.account_id AND p.id = f.product_id WHERE f.account_id = ? AND f.customer_id = ? ORDER BY f.created_at DESC', [customer.accountId, customer.customerId]));
  if (area === 'favorites' && id && request.method === 'POST') { if (!published(account.store_product_ids, id) || !await repo.first<{ id: string }>('SELECT id FROM Product WHERE account_id = ? AND id = ? LIMIT 1', [customer.accountId, id])) return json({ error: 'Product not found' }, { status: 404 }); await repo.run('INSERT OR IGNORE INTO StoreCustomerFavorite (id, account_id, customer_id, product_id, created_at) VALUES (?, ?, ?, ?, ?)', [crypto.randomUUID(), customer.accountId, customer.customerId, id, now]); return json({ saved: true }, { status: 201 }); }
  if (area === 'favorites' && id && request.method === 'DELETE') { await repo.run('DELETE FROM StoreCustomerFavorite WHERE account_id = ? AND customer_id = ? AND product_id = ?', [customer.accountId, customer.customerId, id]); return json({ deleted: true }); }

  if (area === 'registries' && request.method === 'GET') { const rows = await repo.all<Record<string, unknown>>('SELECT r.id, r.share_code, r.title, r.event_date, r.message, r.active, r.created_at, r.updated_at, COUNT(i.id) AS item_count FROM StoreGiftRegistry r LEFT JOIN StoreGiftRegistryItem i ON i.account_id = r.account_id AND i.registry_id = r.id WHERE r.account_id = ? AND r.customer_id = ? GROUP BY r.id ORDER BY r.updated_at DESC', [customer.accountId, customer.customerId]); return json(rows.map((row) => ({ ...row, active: Boolean(row.active), item_count: Number(row.item_count || 0) }))); }
  if (area === 'registries' && request.method === 'POST') { const input = await body(request); const title = string(input?.title, 2, 120); const eventDate = string(input?.event_date, 0, 40); const message = string(input?.message, 0, 1000); const ids = Array.isArray(input?.product_ids) ? [...new Set(input.product_ids.map(String).filter(Boolean))] : []; if (!title || eventDate === null || message === null || !ids.length || ids.length > 100 || ids.some((productId) => !published(account.store_product_ids, productId))) return json({ error: 'Invalid gift registry' }, { status: 400 }); const products = await repo.all<{ id: string }>(`SELECT id FROM Product WHERE account_id = ? AND id IN (${ids.map(() => '?').join(', ')})`, [customer.accountId, ...ids]); if (products.length !== ids.length) return json({ error: 'A selected registry item no longer exists.' }, { status: 400 }); const registryId = crypto.randomUUID(); const shareCode = crypto.randomUUID().replaceAll('-', '').slice(0, 18); await repo.batch([{ query: 'INSERT INTO StoreGiftRegistry (id, account_id, customer_id, share_code, title, event_date, message, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)', values: [registryId, customer.accountId, customer.customerId, shareCode, title, eventDate, message, now, now] }, ...ids.map((productId) => ({ query: 'INSERT INTO StoreGiftRegistryItem (id, account_id, registry_id, product_id, created_at) VALUES (?, ?, ?, ?, ?)', values: [crypto.randomUUID(), customer.accountId, registryId, productId, now] }))]); return json({ id: registryId, share_code: shareCode }, { status: 201 }); }

  if (area === 'gallery' && request.method === 'GET') { const [collections, customOrders, gallery] = await Promise.all([repo.all<Record<string, unknown>>('SELECT id, collection_name, label_text, collection_size FROM StoreCustomerCollection WHERE account_id = ? AND customer_id = ? ORDER BY updated_at DESC', [customer.accountId, customer.customerId]), repo.all<Record<string, unknown>>(`SELECT i.id, i.product_name, i.product_image_data, i.customization_json, o.order_number FROM StoreOrderItem i JOIN StoreOrder o ON o.account_id = i.account_id AND o.id = i.order_id JOIN Product p ON p.account_id = i.account_id AND p.id = i.product_id WHERE o.account_id = ? AND o.customer_id = ? AND o.payment_status = 'paid' AND p.product_type = 'custom' ORDER BY o.paid_at DESC`, [customer.accountId, customer.customerId]), repo.all<Record<string, unknown>>('SELECT id, source_type, source_id, title, image_data, details, status, created_at FROM StoreCustomerGalleryItem WHERE account_id = ? AND customer_id = ? ORDER BY updated_at DESC', [customer.accountId, customer.customerId])]); return json({ collections: collections.map((row) => ({ ...row, source_type: 'collection', title: row.collection_name, details: row.label_text || `${row.collection_size}-candle collection`, image_data: '' })), custom_orders: customOrders.map((row) => ({ ...row, source_type: 'custom_order', title: row.product_name, details: row.customization_json || row.order_number, image_data: row.product_image_data || '' })), gallery }); }
  if (area === 'gallery' && request.method === 'POST') { const input = await body(request); const sourceType = String(input?.source_type || ''); const sourceId = string(input?.source_id, 1, 200); const title = string(input?.title, 2, 120); const image = string(input?.image_data, 0, 2_500_000); if (!['collection', 'custom_order'].includes(sourceType) || !sourceId || !title || image === null) return json({ error: 'Invalid gallery submission' }, { status: 400 }); let details = ''; let defaultImage = ''; if (sourceType === 'collection') { const source = await repo.first<Record<string, unknown>>('SELECT label_text, collection_size FROM StoreCustomerCollection WHERE account_id = ? AND customer_id = ? AND id = ?', [customer.accountId, customer.customerId, sourceId]); if (!source) return json({ error: 'Saved collection not found.' }, { status: 404 }); details = String(source.label_text || '') || `${source.collection_size}-candle collection`; } else { const source = await repo.first<Record<string, unknown>>(`SELECT i.product_image_data, i.customization_json, o.order_number FROM StoreOrderItem i JOIN StoreOrder o ON o.account_id = i.account_id AND o.id = i.order_id JOIN Product p ON p.account_id = i.account_id AND p.id = i.product_id WHERE o.account_id = ? AND o.customer_id = ? AND i.id = ? AND o.payment_status = 'paid' AND p.product_type = 'custom' LIMIT 1`, [customer.accountId, customer.customerId, sourceId]); if (!source) return json({ error: 'Paid custom candle not found.' }, { status: 404 }); details = String(source.customization_json || source.order_number || ''); defaultImage = String(source.product_image_data || ''); } await repo.run("INSERT INTO StoreCustomerGalleryItem (id, account_id, customer_id, source_type, source_id, title, image_data, details, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?) ON CONFLICT(account_id, customer_id, source_type, source_id) DO UPDATE SET title = excluded.title, image_data = excluded.image_data, details = excluded.details, status = 'pending', updated_at = excluded.updated_at", [crypto.randomUUID(), customer.accountId, customer.customerId, sourceType, sourceId, title, image || defaultImage, details, now, now]); return json({ submitted: true }, { status: 201 }); }

  if (area === 'reviews' && request.method === 'POST') { const input = await body(request); const productId = string(input?.product_id, 1, 200); const rating = Number(input?.rating); const title = string(input?.title, 0, 120); const review = string(input?.body, 10, 2000); const photo = string(input?.photo_data, 0, 6_000_000); if (!productId || !Number.isInteger(rating) || rating < 1 || rating > 5 || title === null || !review || photo === null || !published(account.store_product_ids, productId)) return json({ error: 'Invalid review' }, { status: 400 }); const product = await repo.first<{ id: string }>('SELECT id FROM Product WHERE account_id = ? AND id = ? LIMIT 1', [customer.accountId, productId]); if (!product) return json({ error: 'Product not found' }, { status: 404 }); const purchased = await repo.first<{ id: string }>("SELECT i.id FROM StoreOrderItem i JOIN StoreOrder o ON o.account_id = i.account_id AND o.id = i.order_id WHERE o.account_id = ? AND o.customer_id = ? AND i.product_id = ? AND o.payment_status = 'paid' LIMIT 1", [customer.accountId, customer.customerId, productId]); await repo.run("INSERT INTO StoreProductReview (id, account_id, customer_id, product_id, rating, title, body, photo_data, status, verified_purchase, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?) ON CONFLICT(account_id, customer_id, product_id) DO UPDATE SET rating = excluded.rating, title = excluded.title, body = excluded.body, photo_data = excluded.photo_data, status = 'pending', verified_purchase = excluded.verified_purchase, updated_at = excluded.updated_at", [crypto.randomUUID(), customer.accountId, customer.customerId, productId, rating, title, review, photo, purchased ? 1 : 0, now, now]); return json({ submitted: true, verified_purchase: Boolean(purchased) }, { status: 201 }); }
  return null;
}
