import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createD1Repository } from '../lib/d1';
import { readBearerToken } from '../lib/auth';

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function object(request: Request) { return request.json().then((value) => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null).catch(() => null); }
function text(value: unknown, min: number, max: number) { const result = String(value ?? '').trim(); return result.length >= min && result.length <= max ? result : ''; }
function password(value: unknown) { const result = String(value ?? ''); return result.length >= 6 && result.length <= 200 ? result : ''; }
function hash(value: string) { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(value, salt, 64).toString('hex')}`; }
function verify(value: string, stored: string) { const [salt, expectedHex] = String(stored || '').split(':'); if (!salt || !/^[0-9a-f]{128}$/i.test(expectedHex)) return false; const expected = new Uint8Array(expectedHex.length / 2); for (let index = 0; index < expected.length; index += 1) expected[index] = Number.parseInt(expectedHex.slice(index * 2, index * 2 + 2), 16); const actual = scryptSync(value, salt, 64); return actual.length === expected.length && timingSafeEqual(actual, expected); }
function joinCode() { return randomBytes(4).toString('hex').toUpperCase(); }
function clientIp(request: Request) { return String(request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || '').split(',')[0].trim().slice(0, 120); }
function userPayload(row: Record<string, unknown>, token: string, expiresAt: string) { return { token, user: { user_id: row.user_id, account_id: row.account_id, account_name: row.account_name, plan_tier: row.plan_tier || 'free', join_code: row.join_code || '', username: row.name || row.username, email: row.email || '', role: row.role, expires_at: expiresAt } }; }
async function session(repo: ReturnType<typeof createD1Repository>, row: Record<string, unknown>, event: string, request: Request) { const now = new Date().toISOString(); const expiresAt = new Date(Date.now() + 30 * 86400000).toISOString(); const token = randomBytes(32).toString('hex'); await repo.batch([{ query: 'INSERT INTO AuthSession (id, account_user_id, token, expires_at, created_at) VALUES (?, ?, ?, ?, ?)', values: [crypto.randomUUID(), row.user_id, token, expiresAt, now] }, { query: 'INSERT INTO AuthEvent (id, account_id, account_user_id, email, event_type, ip_address, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', values: [crypto.randomUUID(), row.account_id, row.user_id, String(row.email || ''), event, clientIp(request), now] }]); return userPayload(row, token, expiresAt); }

export async function handlePublicAuthRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname; const repo = createD1Repository(db);
  if (path === '/api/auth/bootstrap-status' && request.method === 'GET') { const row = await repo.first<{ count: number }>('SELECT COUNT(*) AS count FROM Account'); return json({ has_accounts: Number(row?.count || 0) > 0 }); }
  if (path === '/api/auth/logout' && request.method === 'POST') { const token = readBearerToken(request); if (token) await repo.run('DELETE FROM AuthSession WHERE token = ?', [token]); return new Response(null, { status: 204 }); }
  if (!['/api/auth/register', '/api/auth/login', '/api/auth/request-access'].includes(path) || request.method !== 'POST') return null;
  const input = await object(request);
  try {
    if (path === '/api/auth/register') {
      const name = text(input?.name, 2, 120); const email = text(input?.email, 3, 254).toLowerCase(); const pass = password(input?.password); if (!name || !EMAIL.test(email) || !pass || pass !== String(input?.password_confirm || '')) return json({ error: 'Invalid registration data' }, { status: 400 });
      if (await repo.first<{ id: string }>('SELECT id FROM Account WHERE lower(name) = ? LIMIT 1', [name.toLowerCase()])) return json({ error: 'Account name already exists' }, { status: 409 }); if (await repo.first<{ id: string }>('SELECT id FROM AccountUser WHERE lower(email) = ? LIMIT 1', [email])) return json({ error: 'Email already in use' }, { status: 409 });
      const accountId = crypto.randomUUID(); const userId = crypto.randomUUID(); const now = new Date().toISOString(); const code = joinCode(); await repo.batch([{ query: 'INSERT INTO Account (id, name, join_code, created_at) VALUES (?, ?, ?, ?)', values: [accountId, name, code, now] }, { query: 'INSERT INTO AccountUser (id, account_id, name, email, username, password_hash, role, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)', values: [userId, accountId, name, email, email, hash(pass), 'owner', now, now] }]); return json(await session(repo, { user_id: userId, account_id: accountId, account_name: name, plan_tier: 'free', join_code: code, name, email, role: 'owner' }, 'register', request), { status: 201 });
    }
    if (path === '/api/auth/login') {
      const identifier = text(input?.identifier, 2, 254).toLowerCase(); const pass = password(input?.password); if (!identifier || !pass) return json({ error: 'Invalid email/account name or password' }, { status: 401 }); const row = await repo.first<Record<string, unknown>>(`SELECT u.id AS user_id, u.account_id, u.name, u.email, u.username, u.password_hash, u.role, u.active, a.name AS account_name, a.plan_tier, a.join_code, a.is_banned, a.access_disabled, a.ban_reason, a.disable_reason FROM AccountUser u JOIN Account a ON a.id = u.account_id WHERE lower(u.email) = ? OR (lower(a.name) = ? AND u.role = 'owner') LIMIT 1`, [identifier, identifier]); if (!row || Number(row.active) !== 1 || !verify(pass, String(row.password_hash))) return json({ error: 'Invalid email/account name or password' }, { status: 401 }); if (Number(row.is_banned)) return json({ error: row.ban_reason ? `Account is banned: ${String(row.ban_reason)}` : 'Account is banned' }, { status: 403 }); if (Number(row.access_disabled)) return json({ error: row.disable_reason ? `Account access is disabled: ${String(row.disable_reason)}` : 'Account access is disabled' }, { status: 403 }); return json(await session(repo, row, 'login', request));
    }
    const accountName = text(input?.account_name, 2, 120); const code = text(input?.join_code, 4, 40).toUpperCase(); const name = text(input?.name, 2, 120); const email = text(input?.email, 3, 254).toLowerCase(); const pass = password(input?.password); if (!accountName || !code || !name || !EMAIL.test(email) || !pass || pass !== String(input?.password_confirm || '')) return json({ error: 'Invalid access request' }, { status: 400 }); const account = await repo.first<Record<string, unknown>>('SELECT id, join_code, is_banned, access_disabled, ban_reason, disable_reason FROM Account WHERE lower(name) = ? LIMIT 1', [accountName.toLowerCase()]); if (!account) return json({ error: 'Account not found' }, { status: 404 }); if (String(account.join_code).toUpperCase() !== code) return json({ error: 'Invalid join code' }, { status: 401 }); if (Number(account.is_banned) || Number(account.access_disabled)) return json({ error: 'Account is unavailable' }, { status: 403 }); const existing = await repo.first<{ id: string }>("SELECT id FROM AccountUser WHERE account_id = ? AND (lower(username) = ? OR lower(email) = ?) LIMIT 1", [account.id, email, email]); if (existing) return json({ error: 'Username already exists in this account' }, { status: 409 }); if (await repo.first<{ id: string }>("SELECT id FROM AccountJoinRequest WHERE account_id = ? AND lower(email) = ? AND status = 'pending' LIMIT 1", [account.id, email])) return json({ error: 'A pending request already exists for this username' }, { status: 409 }); const now = new Date().toISOString(); await repo.batch([{ query: "INSERT INTO AccountJoinRequest (id, account_id, name, email, username, password_hash, requested_role, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'member', 'pending', ?, ?)", values: [crypto.randomUUID(), account.id, name, email, email, hash(pass), now, now] }, { query: "INSERT INTO AuthEvent (id, account_id, account_user_id, email, event_type, ip_address, created_at) VALUES (?, ?, NULL, ?, 'join_request', ?, ?)", values: [crypto.randomUUID(), account.id, email, clientIp(request), now] }]); return json({ ok: true, message: 'Request sent. An account admin must approve it before you can sign in.' }, { status: 201 });
  } catch (error) { return json({ error: error instanceof Error ? error.message : 'Authentication failed' }, { status: 500 }); }
}
