import { resolveStoreCustomer } from '../lib/customerAuth';
import { createD1Repository } from '../lib/d1';
import { expireUnpaidReservations } from '../lib/storeCheckout';

function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function decode(value: string) { try { return decodeURIComponent(value).trim(); } catch { return ''; } }

export async function handlePublicCustomerCommerceRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  if (!db) return null; const path = new URL(request.url).pathname;
  const match = path.match(/^\/api\/public\/store\/([^/]+)\/(orders(?:\/([^/]+))?|customers\/subscriptions(?:\/([^/]+))?)$/); if (!match) return null;
  const slug = decode(match[1]); if (!slug) return json({ error: 'Invalid store slug' }, { status: 400 }); const customer = await resolveStoreCustomer(db, request, slug); if (!customer) return json({ error: 'Unauthorized' }, { status: 401 });
  const repo = createD1Repository(db); const isOrders = path.includes('/orders'); const isSubscriptions = path.includes('/customers/subscriptions'); const id = decode(match[3] || match[4] || ''); const now = new Date().toISOString();
  if (isOrders && !id && request.method === 'GET') { await expireUnpaidReservations(repo, customer.accountId, now); return json(await repo.all<Record<string, unknown>>('SELECT id, order_number, status, payment_status, fulfillment_status, currency, total_amount, created_at, updated_at FROM StoreOrder WHERE account_id = ? AND customer_id = ? ORDER BY created_at DESC', [customer.accountId, customer.customerId])); }
  if (isOrders && id && request.method === 'GET') { const order = await repo.first<Record<string, unknown>>('SELECT id, order_number, status, payment_status, fulfillment_status, currency, total_amount, customer_note, shipping_recipient_name, shipping_street_address_1, shipping_street_address_2, shipping_city, shipping_state_region, shipping_postal_code, shipping_country, tracking_number, created_at, updated_at FROM StoreOrder WHERE account_id = ? AND customer_id = ? AND id = ? LIMIT 1', [customer.accountId, customer.customerId, id]); if (!order) return json({ error: 'Order not found' }, { status: 404 }); const [items, payments] = await Promise.all([repo.all<Record<string, unknown>>('SELECT id, product_name, product_image_data, unit_price, quantity, line_total FROM StoreOrderItem WHERE account_id = ? AND order_id = ? ORDER BY created_at', [customer.accountId, id]), repo.all<Record<string, unknown>>('SELECT id, provider, status, amount, currency, created_at FROM StoreOrderPayment WHERE account_id = ? AND order_id = ? ORDER BY created_at', [customer.accountId, id])]); return json({ ...order, items, payments }); }
  if (isSubscriptions && !id && request.method === 'GET') return json(await repo.all<Record<string, unknown>>('SELECT s.id, s.status, s.cadence, s.shipping_address_id, s.next_shipment_at, s.skip_next, s.payment_status, p.name AS plan_name, p.candle_count FROM StoreCustomerSubscription s JOIN StoreSubscriptionPlan p ON p.account_id = s.account_id AND p.id = s.plan_id WHERE s.account_id = ? AND s.customer_id = ? ORDER BY s.updated_at DESC', [customer.accountId, customer.customerId]).then((rows) => rows.map((row) => ({ ...row, skip_next: Boolean(row.skip_next) }))));
  if (isSubscriptions && id && request.method === 'PATCH') { const input = await body(request); const action = String(input?.action || ''); if (!['skip', 'pause', 'resume', 'cancel', 'address'].includes(action)) return json({ error: 'Invalid subscription action' }, { status: 400 }); const subscription = await repo.first<{ id: string; status: string; shipping_address_id: string | null }>('SELECT id, status, shipping_address_id FROM StoreCustomerSubscription WHERE account_id = ? AND customer_id = ? AND id = ? LIMIT 1', [customer.accountId, customer.customerId, id]); if (!subscription) return json({ error: 'Subscription not found.' }, { status: 404 }); let addressId = subscription.shipping_address_id; if (action === 'address') { addressId = String(input?.shipping_address_id || '').trim(); const address = addressId && await repo.first<{ id: string }>('SELECT id FROM StoreCustomerAddress WHERE account_id = ? AND customer_id = ? AND id = ? LIMIT 1', [customer.accountId, customer.customerId, addressId]); if (!address) return json({ error: 'Saved shipping address not found.' }, { status: 400 }); } const status = action === 'pause' ? 'paused' : action === 'resume' ? 'active' : action === 'cancel' ? 'cancelled' : subscription.status; await repo.run('UPDATE StoreCustomerSubscription SET status = ?, skip_next = ?, shipping_address_id = ?, updated_at = ? WHERE account_id = ? AND customer_id = ? AND id = ?', [status, action === 'skip' ? 1 : 0, addressId, now, customer.accountId, customer.customerId, id]); return json({ updated: true }); }
  return null;
}
