import { canEditFeature, resolveAuthContext } from '../lib/auth';
const IMAGE_TYPES: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif' };
const FONT_TYPES: Record<string, string> = { ttf: 'font/ttf', otf: 'font/otf', woff: 'font/woff', woff2: 'font/woff2' };
type MediaObject = { body: ReadableStream; httpEtag: string; writeHttpMetadata(headers: Headers): void };
function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function bytes(base64: string) { const binary = atob(base64); const result = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i += 1) result[i] = binary.charCodeAt(i); return result; }
export async function handleStorefrontMediaRequest(request: Request, db: D1Database | undefined, media: R2Bucket | undefined): Promise<Response | null> {
  const url = new URL(request.url); const publicMatch = url.pathname.match(/^\/(store-media|store-fonts)\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9._-]+)$/);
  if (publicMatch && request.method === 'GET') { if (!media) return json({ error: 'Media storage is not configured' }, { status: 503 }); const key = `${publicMatch[1] === 'store-media' ? 'images' : 'fonts'}/${publicMatch[2]}/${publicMatch[3]}`; const object = await media.get(key) as unknown as MediaObject | null; if (!object) return new Response('Not found', { status: 404 }); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('etag', object.httpEtag); headers.set('cache-control', 'public, max-age=31536000, immutable'); return new Response(object.body, { headers }); }
  if (!db || !media || request.method !== 'POST' || !['/api/storefront/upload-image', '/api/storefront/upload-font'].includes(url.pathname)) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 }); let input: Record<string, unknown> | null = null; try { const value = await request.json(); input = value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { /* invalid */ }
  const dataUrl = String(input?.data_url ?? ''); const font = url.pathname.endsWith('upload-font'); const match = dataUrl.match(/^data:([^;]+);base64,([A-Za-z0-9+/=]+)$/i); if (!match) return json({ error: font ? 'Invalid font data' : 'Invalid image format' }, { status: 400 }); const mime = match[1].toLowerCase(); const ext = font ? String(input?.file_name ?? '').trim().split('.').pop()?.toLowerCase() || '' : Object.entries(IMAGE_TYPES).find(([, type]) => type === mime)?.[0] || ''; if ((font ? FONT_TYPES[ext] !== mime : !IMAGE_TYPES[ext])) return json({ error: font ? 'Unsupported font format. Use TTF, OTF, WOFF, or WOFF2.' : 'Invalid image format' }, { status: 400 }); let body: Uint8Array; try { body = bytes(match[2]); } catch { return json({ error: 'Invalid upload data' }, { status: 400 }); } if (body.byteLength > (font ? 12 : 8) * 1024 * 1024) return json({ error: `${font ? 'Font' : 'Image'} file is too large` }, { status: 413 }); const normalizedExt = ext === 'jpeg' ? 'jpg' : ext; const file = `${Date.now()}-${crypto.randomUUID().replaceAll('-', '')}.${normalizedExt}`; const prefix = font ? 'fonts' : 'images'; await media.put(`${prefix}/${auth.accountId}/${file}`, body, { httpMetadata: { contentType: font ? FONT_TYPES[ext] : IMAGE_TYPES[ext] } }); const response: Record<string, string> = { url: `/${font ? 'store-fonts' : 'store-media'}/${auth.accountId}/${file}` }; if (font) { const raw = String(input?.file_name ?? '').trim(); response.family = (raw.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9 _-]/g, '').trim().slice(0, 80) || `Font-${Date.now()}`).replace(/\s+/g, ' '); response.original_name = raw; } return json(response, { status: 201 });
}
