import { canEditFeature, resolveAuthContext } from '../lib/auth';
import { createD1Repository } from '../lib/d1';

const IMAGE_TYPES: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif' };
const FONT_TYPES: Record<string, string> = { ttf: 'font/ttf', otf: 'font/otf', woff: 'font/woff', woff2: 'font/woff2' };
const MAX_MEDIA_BYTES = 1_500_000;

function json(body: unknown, init: ResponseInit = {}) { const headers = new Headers(init.headers); headers.set('content-type', 'application/json; charset=utf-8'); headers.set('cache-control', 'no-store'); return new Response(JSON.stringify(body), { ...init, headers }); }
function decoded(value: string) { try { return decodeURIComponent(value).trim(); } catch { return ''; } }
function bytes(value: string) { const binary = atob(value); const result = new Uint8Array(binary.length); for (let index = 0; index < binary.length; index += 1) result[index] = binary.charCodeAt(index); return result; }

export async function handleStorefrontMediaRequest(request: Request, db: D1Database | undefined): Promise<Response | null> {
  const url = new URL(request.url); const publicMatch = url.pathname.match(/^\/(store-media|store-fonts)\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9._-]+)$/);
  if (publicMatch && request.method === 'GET') { if (!db) return json({ error: 'Database is not configured' }, { status: 503 }); const item = await createD1Repository(db).first<{ content_type: string; body: ArrayBuffer }>('SELECT content_type, body FROM StorefrontMedia WHERE account_id = ? AND file_name = ? AND kind = ? LIMIT 1', [decoded(publicMatch[2]), decoded(publicMatch[3]), publicMatch[1] === 'store-media' ? 'image' : 'font']); if (!item) return new Response('Not found', { status: 404 }); return new Response(item.body, { headers: { 'content-type': item.content_type, 'cache-control': 'public, max-age=31536000, immutable' } }); }
  if (!db || request.method !== 'POST' || !['/api/storefront/upload-image', '/api/storefront/upload-font'].includes(url.pathname)) return null;
  const auth = await resolveAuthContext(db, request); if (!auth) return json({ error: 'Unauthorized' }, { status: 401 }); if (!await canEditFeature(db, auth, 'storefront_edit')) return json({ error: 'Forbidden' }, { status: 403 });
  let input: Record<string, unknown> | null = null; try { const value = await request.json(); input = value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return json({ error: 'Invalid upload request' }, { status: 400 }); }
  const dataUrl = String(input?.data_url ?? ''); const font = url.pathname.endsWith('upload-font'); const match = dataUrl.match(/^data:([^;]+);base64,([A-Za-z0-9+/=]+)$/i); if (!match) return json({ error: font ? 'Invalid font data' : 'Invalid image format' }, { status: 400 }); const contentType = match[1].toLowerCase(); const extension = font ? String(input?.file_name ?? '').trim().split('.').pop()?.toLowerCase() || '' : Object.entries(IMAGE_TYPES).find(([, value]) => value === contentType)?.[0] || ''; if ((font && FONT_TYPES[extension] !== contentType) || (!font && !IMAGE_TYPES[extension])) return json({ error: font ? 'Unsupported font format' : 'Invalid image format' }, { status: 400 });
  let body: Uint8Array; try { body = bytes(match[2]); } catch { return json({ error: 'Invalid upload data' }, { status: 400 }); } if (body.byteLength > MAX_MEDIA_BYTES) return json({ error: 'Free-tier media uploads are limited to 1.5 MB per file' }, { status: 413 });
  const fileName = `${Date.now()}-${crypto.randomUUID().replaceAll('-', '')}.${extension === 'jpeg' ? 'jpg' : extension}`; const kind = font ? 'font' : 'image'; await createD1Repository(db).run('INSERT INTO StorefrontMedia (id, account_id, file_name, kind, content_type, body, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), auth.accountId, fileName, kind, contentType, body, new Date().toISOString()]); const response: Record<string, string> = { url: `/${font ? 'store-fonts' : 'store-media'}/${auth.accountId}/${fileName}` }; if (font) { const originalName = String(input?.file_name ?? '').trim(); response.family = (originalName.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9 _-]/g, '').trim().slice(0, 80) || `Font-${Date.now()}`).replace(/\s+/g, ' '); response.original_name = originalName; } return json(response, { status: 201 });
}
