import { useEffect, useState, type FormEvent } from 'react';
import { localDb, type StoreCustomScentRequestRecord, type StoreScentPollRecord } from '../../lib/localDb';

export default function LaunchToolsManager({ readOnly }: { readOnly: boolean }) {
  const [polls, setPolls] = useState<StoreScentPollRecord[]>([]);
  const [requests, setRequests] = useState<StoreCustomScentRequestRecord[]>([]);
  const [status, setStatus] = useState('');
  const [form, setForm] = useState({ title: '', poll_type: 'next_scent' as 'next_scent' | 'retired_scent', options: '' });
  const load = async () => { try { const data = await localDb.getStorefrontLaunchTools(); setPolls(data.polls); setRequests(data.requests); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to load launch tools.'); } };
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); try { await localDb.createStorefrontScentPoll({ title: form.title, poll_type: form.poll_type, options: form.options.split(',').map((value) => value.trim()).filter(Boolean) }); setForm({ title: '', poll_type: 'next_scent', options: '' }); await load(); setStatus('Poll published.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to publish poll.'); } }
  return <section className="mt-8 rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold text-gray-800">Launch Tools</h3><p className="mt-1 text-sm text-gray-600">Publish scent polls and review incoming custom scent requests.</p>{status ? <p className="mt-3 text-sm text-gray-700">{status}</p> : null}<form onSubmit={(event) => void create(event)} className="mt-4 grid gap-3 rounded-lg bg-gray-50 p-4 md:grid-cols-4"><input disabled={readOnly} required value={form.title} onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))} placeholder="Poll question" className="rounded border border-gray-300 px-3 py-2 md:col-span-2" /><select disabled={readOnly} value={form.poll_type} onChange={(e) => setForm((p) => ({ ...p, poll_type: e.target.value as 'next_scent' | 'retired_scent' }))} className="rounded border border-gray-300 px-3 py-2"><option value="next_scent">Next scent</option><option value="retired_scent">Bring back a scent</option></select><input disabled={readOnly} required value={form.options} onChange={(e) => setForm((p) => ({ ...p, options: e.target.value }))} placeholder="Options, comma separated" className="rounded border border-gray-300 px-3 py-2" /><button disabled={readOnly} className="rounded bg-pink-600 px-4 py-2 font-semibold text-white disabled:opacity-60 md:col-span-4">Publish poll</button></form><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h4 className="font-bold text-gray-800">Polls</h4><div className="mt-2 space-y-2">{polls.length ? polls.map((poll) => <div key={poll.id} className="rounded-lg border border-gray-200 p-3"><p className="font-semibold">{poll.title}</p><p className="text-xs text-gray-500">{poll.poll_type.replace('_', ' ')} | {poll.active ? 'Active' : 'Closed'}{poll.active ? '' : ` | ${Number(poll.vote_count || 0)} vote${Number(poll.vote_count || 0) === 1 ? '' : 's'}`}</p><button disabled={readOnly} type="button" onClick={() => void localDb.updateStorefrontScentPoll(poll.id, { active: !poll.active }).then(load)} className="mt-2 text-sm font-semibold text-pink-700">{poll.active ? 'Close poll' : 'Reopen poll'}</button></div>) : <p className="text-sm text-gray-500">No polls yet.</p>}</div></div><div><h4 className="font-bold text-gray-800">Custom scent requests</h4><div className="mt-2 max-h-80 space-y-2 overflow-y-auto">{requests.length ? requests.map((request) => <RequestCard key={request.id} request={request} readOnly={readOnly} reload={load} />) : <p className="text-sm text-gray-500">No requests yet.</p>}</div></div></div></section>;
}
function RequestCard({ request, readOnly, reload }: { request: StoreCustomScentRequestRecord; readOnly: boolean; reload: () => Promise<void> }) { const [notes, setNotes] = useState(request.admin_notes || ''); const [state, setState] = useState(request.status); const [quote, setQuote] = useState(String(request.quote_amount || '')); return <div className="rounded-lg border border-gray-200 p-3 text-sm"><p className="font-semibold text-gray-900">{request.name} <span className="font-normal text-gray-500">{request.email}</span></p><p className="mt-1 text-gray-700">{[request.scent_family, request.desired_notes, request.occasion, request.details].filter(Boolean).join(' | ') || 'No scent details supplied.'}</p><div className="mt-2 flex gap-2"><select disabled={readOnly} value={state} onChange={(e) => setState(e.target.value as StoreCustomScentRequestRecord['status'])} className="rounded border border-gray-300 px-2 py-1"><option value="new">New</option><option value="reviewing">Reviewing</option><option value="quoted">Quoted</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="closed">Closed</option></select><input disabled={readOnly} type="number" min="0" step="0.01" value={quote} onChange={(e) => setQuote(e.target.value)} placeholder="Quote $" className="w-24 rounded border border-gray-300 px-2 py-1" /><button disabled={readOnly} type="button" onClick={() => void localDb.updateStorefrontCustomScentRequest(request.id, { status: state, quote_amount: Number(quote || 0), admin_notes: notes }).then(reload)} className="rounded bg-gray-900 px-2 py-1 font-semibold text-white">Save</button></div><textarea disabled={readOnly} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Quote details or internal notes" rows={2} className="mt-2 w-full rounded border border-gray-300 px-2 py-1" /></div>; }
