import type { HtmlPresetId, HtmlPresetModel } from './presetBuilder.types';

export function getDefaultPresetModel(presetId: HtmlPresetId): HtmlPresetModel {
  if (presetId === 'coastal-breeze') {
    return {
      pageTitle: 'Coastal Breeze Candles',
      metaDescription: 'Fresh coastal-inspired candles for bright, clean spaces.',
      brandName: 'COASTAL BREEZE',
      brandSubtitle: 'Sea Salt Collection',
      navAbout: 'About',
      navCollection: 'Scents',
      navWhyUs: 'Story',
      navContact: 'Contact',
      eyebrow: 'Fresh Coastal Fragrance',
      heroLine1: 'Ocean air.',
      heroLine2: 'Clean candles.',
      heroLine3: 'Relaxed living.',
      heroDescription: 'Inspired by shoreline mornings and sea breeze evenings.',
      primaryButtonText: 'Shop Scents',
      secondaryButtonText: 'Learn More',
      sectionAboutTitle: 'About Coastal Breeze',
      sectionAboutBody: 'A crisp and calming candle line designed for everyday comfort.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Coastal Collection',
      sectionCollectionBody: 'Sea salt, driftwood, linen, and soft citrus fragrance profiles.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Coastal Breeze',
      whyUsBody: 'Fresh scent performance with clean burn behavior and refined presentation.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Reach out for gifting, custom bundles, and event favors.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#edf7ff',
      textColor: '#0f2940',
      mutedColor: '#3b607d',
      accentColor: '#2c7fb8',
      panelColor: '#ffffff',
    };
  }
  if (presetId === 'botanical-spa') {
    return {
      pageTitle: 'Botanical Spa Candles',
      metaDescription: 'Calming botanical blends for spa-like routines at home.',
      brandName: 'BOTANICAL SPA',
      brandSubtitle: 'Wellness Candle Studio',
      navAbout: 'About',
      navCollection: 'Collection',
      navWhyUs: 'Ingredients',
      navContact: 'Contact',
      eyebrow: 'Botanical Wellness',
      heroLine1: 'Calm mind.',
      heroLine2: 'Soft light.',
      heroLine3: 'Daily ritual.',
      heroDescription: 'Herbal and floral blends crafted to support relaxing routines.',
      primaryButtonText: 'Browse Collection',
      secondaryButtonText: 'Our Ingredients',
      sectionAboutTitle: 'Wellness First',
      sectionAboutBody: 'We focus on soothing scent profiles and balanced throw for mindful spaces.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Spa Collection',
      sectionCollectionBody: 'Lavender, eucalyptus, chamomile, and green tea inspired blends.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Botanical Spa',
      whyUsBody: 'Balanced fragrance profiles built for calm rooms and everyday routines.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Message us for curated wellness bundles and custom selections.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#eef8f1',
      textColor: '#1a2f24',
      mutedColor: '#4f6b5d',
      accentColor: '#3f8f66',
      panelColor: '#f8fff9',
    };
  }
  if (presetId === 'autumn-harvest') {
    return {
      pageTitle: 'Autumn Harvest Candles',
      metaDescription: 'Warm seasonal candles with cozy fall fragrance notes.',
      brandName: 'AUTUMN HARVEST',
      brandSubtitle: 'Seasonal Candle Co.',
      navAbout: 'About',
      navCollection: 'Seasonals',
      navWhyUs: 'Craft',
      navContact: 'Contact',
      eyebrow: 'Limited Fall Collection',
      heroLine1: 'Cozy rooms.',
      heroLine2: 'Spiced scent.',
      heroLine3: 'Golden season.',
      heroDescription: 'Pumpkin, clove, amber, and woodsy notes for fall atmospheres.',
      primaryButtonText: 'Shop Fall Scents',
      secondaryButtonText: 'See Story',
      sectionAboutTitle: 'Crafted for Fall',
      sectionAboutBody: 'Seasonal pours made to feel warm, nostalgic, and inviting.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Harvest Lineup',
      sectionCollectionBody: 'Spice-forward blends with smooth warmth and holiday-ready presentation.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Autumn Harvest',
      whyUsBody: 'Seasonal craftsmanship with warm notes and cozy atmosphere.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Contact us for seasonal gift sets and event candles.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#1f1712',
      textColor: '#f4e7d8',
      mutedColor: '#b89f88',
      accentColor: '#d2863a',
      panelColor: '#2a2019',
    };
  }
  if (presetId === 'midnight-glam') {
    return {
      pageTitle: 'Midnight Glam Candles',
      metaDescription: 'Bold luxury candles with dramatic contrast and premium styling.',
      brandName: 'MIDNIGHT GLAM',
      brandSubtitle: 'Noir Signature Series',
      navAbout: 'About',
      navCollection: 'Noir Line',
      navWhyUs: 'Luxury',
      navContact: 'Contact',
      eyebrow: 'Noir Luxury Candles',
      heroLine1: 'Bold glow.',
      heroLine2: 'Night luxury.',
      heroLine3: 'Statement scent.',
      heroDescription: 'Designed for elevated interiors with dramatic visual style.',
      primaryButtonText: 'Shop Noir',
      secondaryButtonText: 'Brand Story',
      sectionAboutTitle: 'Luxury in Contrast',
      sectionAboutBody: 'Dark palettes, polished vessels, and fragrance with lasting presence.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Noir Collection',
      sectionCollectionBody: 'Deep amber, velvet musk, black orchid, and smoked vanilla.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Midnight Glam',
      whyUsBody: 'Bold styling, premium scent throw, and statement shelf presence.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Get in touch for concierge gifting and candle service inquiries.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#0a0a12',
      textColor: '#f4f1ff',
      mutedColor: '#a59cbf',
      accentColor: '#b987ff',
      panelColor: '#151526',
    };
  }
  if (presetId === 'winter-frost') {
    return {
      pageTitle: 'Winter Frost Candles',
      metaDescription: 'Crisp winter-inspired candles with clean, cool fragrance notes.',
      brandName: 'WINTER FROST',
      brandSubtitle: 'Holiday Candle Atelier',
      navAbout: 'About',
      navCollection: 'Holiday',
      navWhyUs: 'Details',
      navContact: 'Contact',
      eyebrow: 'Winter Seasonal Release',
      heroLine1: 'Cool air.',
      heroLine2: 'Warm flame.',
      heroLine3: 'Holiday glow.',
      heroDescription: 'Snowy, minty, and pine-forward scents for winter homes and gifting.',
      primaryButtonText: 'Shop Winter',
      secondaryButtonText: 'Gift Guide',
      sectionAboutTitle: 'Winter Mood',
      sectionAboutBody: 'A frosty palette and crisp scent lineup tailored for the season.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Holiday Collection',
      sectionCollectionBody: 'Frosted pine, peppermint cream, cedar smoke, and winter citrus.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Winter Frost',
      whyUsBody: 'Crisp seasonal notes with clean visual style and gift-ready packaging.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Reach out for holiday orders and custom gift runs.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#f0f5ff',
      textColor: '#1d2a40',
      mutedColor: '#5d7191',
      accentColor: '#4d7fd1',
      panelColor: '#ffffff',
    };
  }
  if (presetId === 'minimal-clean') {
    return {
      pageTitle: 'My Candle Store',
      metaDescription: 'Handcrafted candles made with care.',
      brandName: 'MY CANDLE STORE',
      brandSubtitle: 'Handcrafted Collection',
      navAbout: 'About',
      navCollection: 'Collection',
      navWhyUs: 'Why Us',
      navContact: 'Contact',
      eyebrow: 'Clean Home Fragrance',
      heroLine1: 'Simple light.',
      heroLine2: 'Clean scent.',
      heroLine3: 'Everyday comfort.',
      heroDescription:
        'Our candles are designed for daily use with balanced fragrance and clean presentation.',
      primaryButtonText: 'Shop Collection',
      secondaryButtonText: 'Contact',
      sectionAboutTitle: 'About',
      sectionAboutBody: 'A modern candle line focused on quality ingredients and consistent results.',
      sectionAboutImage: '',
      showAboutSection: true,
      sectionCollectionTitle: 'Featured Candles',
      sectionCollectionBody:
        'Choose from curated scents designed for living rooms, bedrooms, and gifting.',
      collectionCarouselImages: [],
      collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
      collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
      collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
      collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
      collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
      showCollectionSection: true,
      extraSections: [],
      whyUsTitle: 'Why Choose Us',
      whyUsBody: 'Small-batch pours, balanced fragrance, and clean design for modern homes.',
      whyUsImage: '',
      showWhyUsSection: true,
      contactTitle: 'Contact',
      contactBody: 'Reach out for custom orders, gifts, and special requests.',
      contactImage: '',
      showContactSection: true,
      textStyles: {},
      uploadedFonts: [],
      savedColors: [],
      footerText: 'All rights reserved.',
      bgColor: '#f5f7fb',
      textColor: '#111827',
      mutedColor: '#4b5563',
      accentColor: '#2563eb',
      panelColor: '#ffffff',
    };
  }

  return {
    pageTitle: 'KACHA MATON | The Signature Collection',
    metaDescription:
      'KACHA MATON creates luxury hand-poured candles with rich fragrance and elegant design.',
    brandName: 'KACHA MATON',
    brandSubtitle: 'The Signature Collection',
    navAbout: 'About',
    navCollection: 'Collection',
    navWhyUs: 'Why Us',
    navContact: 'Contact',
    eyebrow: 'Luxury Hand-Poured Candles',
    heroLine1: 'Warm light.',
    heroLine2: 'Rich fragrance.',
    heroLine3: 'Timeless presence.',
    heroDescription:
      'KACHA MATON is built on craftsmanship, presentation, and atmosphere for elevated spaces.',
    primaryButtonText: 'Explore the Collection',
    secondaryButtonText: 'Get in Touch',
    sectionAboutTitle: 'About the Brand',
    sectionAboutBody:
      'Elegant candles with a strong identity, refined styling, and fragrance that leaves an impression.',
    sectionAboutImage: '',
    showAboutSection: true,
    sectionCollectionTitle: 'The Collection',
    sectionCollectionBody:
      'Designed for homes, gifts, and people who appreciate products with character.',
    collectionCarouselImages: [],
    collectionCarouselImage1: 'https://theme-land.com/sapp/demo/assets/img/screenshots/3.jpg',
    collectionCarouselImage2: 'https://theme-land.com/sapp/demo/assets/img/screenshots/1.jpg',
    collectionCarouselImage3: 'https://theme-land.com/sapp/demo/assets/img/screenshots/5.jpg',
    collectionCarouselImage4: 'https://theme-land.com/sapp/demo/assets/img/screenshots/4.jpg',
    collectionCarouselImage5: 'https://theme-land.com/sapp/demo/assets/img/screenshots/2.jpg',
    showCollectionSection: true,
    extraSections: [],
    whyUsTitle: 'Why Choose Us',
    whyUsBody:
      'We focus on quality materials, clean pours, and scent performance you can trust from batch to batch.',
    whyUsImage: '',
    showWhyUsSection: true,
    contactTitle: 'Contact',
    contactBody: 'Contact us for custom orders, gifting, or special requests.',
    contactImage: '',
    showContactSection: true,
    textStyles: {},
    uploadedFonts: [],
    savedColors: [],
    footerText: 'All rights reserved.',
    bgColor: '#050505',
    textColor: '#f2f2f2',
    mutedColor: '#a8a8a8',
    accentColor: '#d4af37',
    panelColor: '#171717',
  };
}

export function buildDefaultPresetModelsById(): Record<HtmlPresetId, HtmlPresetModel> {
  return {
    'luxury-signature': getDefaultPresetModel('luxury-signature'),
    'minimal-clean': getDefaultPresetModel('minimal-clean'),
    'coastal-breeze': getDefaultPresetModel('coastal-breeze'),
    'botanical-spa': getDefaultPresetModel('botanical-spa'),
    'autumn-harvest': getDefaultPresetModel('autumn-harvest'),
    'midnight-glam': getDefaultPresetModel('midnight-glam'),
    'winter-frost': getDefaultPresetModel('winter-frost'),
  };
}
