import { type FormEvent, useEffect, useState } from 'react';
import { localDb } from '../../lib/localDb';

type Slot = { id: string; starts_at: string; capacity: number; deposit_amount: number; active: boolean; booked: number };
type Booking = { id: string; name: string; email: string; party_size: number; status: 'confirmed' | 'cancelled' | 'attended' | 'no_show'; payment_status: string; starts_at: string; deposit_amount: number };

export default function WorkshopManager({ readOnly }: { readOnly: boolean }) {
  const [slots, setSlots] = useState<Slot[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [form, setForm] = useState({ starts_at: '', capacity: '8', deposit_amount: '0' }); const [message, setMessage] = useState('');
  const load = () => Promise.all([localDb.getStorefrontWorkshops(), localDb.getStorefrontWorkshopBookings()]).then(([nextSlots, nextBookings]) => { setSlots(nextSlots); setBookings(nextBookings); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Unable to load workshops.'));
  useEffect(() => { void load(); }, []);
  async function add(event: FormEvent) { event.preventDefault(); setMessage(''); try { await localDb.createStorefrontWorkshop({ starts_at: new Date(form.starts_at).toISOString(), capacity: Number(form.capacity), deposit_amount: Number(form.deposit_amount) }); setForm({ starts_at: '', capacity: '8', deposit_amount: '0' }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to add workshop.'); } }
  return <section className="mt-6 rounded-xl border bg-white p-5"><h3 className="font-bold">Candle-making workshops</h3><p className="mt-1 text-sm text-slate-600">Create appointment slots, manage capacity, and track customer reservations. Deposits remain pending until a payment provider is configured.</p>{!readOnly ? <form onSubmit={(event) => void add(event)} className="mt-4 grid gap-2 md:grid-cols-4"><input required type="datetime-local" value={form.starts_at} onChange={(event) => setForm({ ...form, starts_at: event.target.value })} className="rounded border p-2" /><input required type="number" min="1" max="100" value={form.capacity} onChange={(event) => setForm({ ...form, capacity: event.target.value })} className="rounded border p-2" placeholder="Capacity" /><input required type="number" min="0" step="0.01" value={form.deposit_amount} onChange={(event) => setForm({ ...form, deposit_amount: event.target.value })} className="rounded border p-2" placeholder="Deposit" /><button className="rounded bg-pink-600 p-2 font-semibold text-white">Add workshop</button></form> : null}{message ? <p className="mt-3 text-sm text-red-700">{message}</p> : null}<div className="mt-4 space-y-2">{slots.map((slot) => <div key={slot.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span>{new Date(slot.starts_at).toLocaleString()} | {Number(slot.booked)}/{slot.capacity} seats | ${Number(slot.deposit_amount).toFixed(2)} deposit | {slot.active ? 'Open' : 'Closed'}</span>{!readOnly ? <button onClick={() => void localDb.updateStorefrontWorkshop(slot.id, !slot.active).then(load)} className="text-pink-700">{slot.active ? 'Close' : 'Reopen'}</button> : null}</div>)}</div><div className="mt-5"><h4 className="font-semibold">Reservations</h4><div className="mt-2 max-h-72 space-y-2 overflow-y-auto">{bookings.map((booking) => <div key={booking.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span><strong>{booking.name}</strong> ({booking.email}) | {new Date(booking.starts_at).toLocaleString()} | {booking.party_size} seats | deposit: {booking.payment_status}</span>{!readOnly ? <select value={booking.status} onChange={(event) => void localDb.updateStorefrontWorkshopBooking(booking.id, event.target.value as Booking['status']).then(load)} className="rounded border p-1"><option value="confirmed">Confirmed</option><option value="attended">Attended</option><option value="no_show">No show</option><option value="cancelled">Cancelled</option></select> : <span>{booking.status}</span>}</div>)}{!bookings.length ? <p className="text-sm text-slate-600">No workshop bookings yet.</p> : null}</div></div></section>;
}
