import { useEffect, useState } from 'react';
import { localDb } from '../../lib/localDb';

type Request = { id: string; name: string; email: string; event_type: string; requested_date: string; party_size: number; details: string; status: 'new' | 'reviewing' | 'quoted' | 'confirmed' | 'declined' | 'closed'; admin_notes: string };

export default function WorkshopPartyManager({ readOnly }: { readOnly: boolean }) {
  const [requests, setRequests] = useState<Request[]>([]); const [message, setMessage] = useState('');
  const load = () => void localDb.getStorefrontWorkshopPartyRequests().then(setRequests).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Unable to load party requests.'));
  useEffect(load, []);
  return <section className="mt-6 rounded-xl border bg-white p-5"><h3 className="font-bold">Private workshop parties</h3><p className="mt-1 text-sm text-slate-600">Review birthday, date-night, bridal, and corporate group requests.</p>{message ? <p className="mt-3 text-sm text-red-700">{message}</p> : null}<div className="mt-4 max-h-96 space-y-3 overflow-y-auto">{requests.map((request) => <div key={request.id} className="rounded border p-3 text-sm"><p><strong>{request.name}</strong> ({request.email}) | {request.event_type.replace('_', ' ')} | {request.party_size} guests {request.requested_date ? `| ${request.requested_date}` : ''}</p>{request.details ? <p className="mt-1 text-slate-600">{request.details}</p> : null}{!readOnly ? <div className="mt-2 grid gap-2 md:grid-cols-[150px_1fr_auto]"><select value={request.status} onChange={(event) => setRequests((items) => items.map((item) => item.id === request.id ? { ...item, status: event.target.value as Request['status'] } : item))} className="rounded border p-2"><option value="new">New</option><option value="reviewing">Reviewing</option><option value="quoted">Quoted</option><option value="confirmed">Confirmed</option><option value="declined">Declined</option><option value="closed">Closed</option></select><input value={request.admin_notes} onChange={(event) => setRequests((items) => items.map((item) => item.id === request.id ? { ...item, admin_notes: event.target.value } : item))} placeholder="Internal notes" className="rounded border p-2" /><button onClick={() => void localDb.updateStorefrontWorkshopPartyRequest(request.id, { status: request.status, admin_notes: request.admin_notes }).then(load)} className="rounded border px-3 text-pink-700">Save</button></div> : <p className="mt-2">Status: {request.status}</p>}</div>)}{!requests.length ? <p className="text-sm text-slate-600">No private-party requests yet.</p> : null}</div></section>;
}
