import { useState, type FormEvent } from "react";
import { localDb } from "../../lib/localDb";
import type { GiftPackOilSelection } from "./FragranceOilCatalogModal";

export default function CollectionRequestModal({ slug, items, collectionSize, onClose }: { slug: string; items: GiftPackOilSelection[]; collectionSize: number; onClose: () => void }) {
  const [form, setForm] = useState({ collection_name: "", label_text: "" });
  const [status, setStatus] = useState("");
  const [sending, setSending] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); const token = window.localStorage.getItem(`candles.store.customer.${slug}`) || ""; if (!token) { setStatus("Sign in through Account before saving a collection."); return; } setSending(true); setStatus(""); try { await localDb.saveStoreCustomerCollection(slug, token, { ...form, collection_size: collectionSize, items }); setStatus("Collection saved to your customer account."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save your collection."); } finally { setSending(false); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={(event) => void submit(event)} className="store-customer-modal mx-auto my-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-gray-900">Create a collection</h2><p className="mt-1 text-sm text-gray-600">Your {collectionSize}-candle collection is saved to your customer account.</p></div><button type="button" onClick={onClose} className="text-sm font-semibold text-pink-700">Close</button></div><div className="mt-5 rounded-lg border border-gray-200 bg-gray-50 p-3"><p className="text-sm font-semibold text-gray-900">Selected candle choices</p><ul className="mt-2 space-y-1 text-sm text-gray-600">{items.map((item) => <li key={`${item.name}-${item.size}-${item.wickCount}-${item.wickType}`}>{item.name}: {item.size}, {item.wickCount}, {item.wickType}</li>)}</ul></div><div className="mt-5 grid gap-3"><input required value={form.collection_name} onChange={(event) => setForm((current) => ({ ...current, collection_name: event.target.value }))} placeholder="Collection name" className="rounded-lg border border-gray-300 px-3 py-2" /><input value={form.label_text} onChange={(event) => setForm((current) => ({ ...current, label_text: event.target.value }))} placeholder="Label text for the collection (optional)" className="rounded-lg border border-gray-300 px-3 py-2" />{status ? <p className="text-sm text-gray-700">{status}</p> : null}<button disabled={sending || Boolean(status)} className="rounded-lg bg-pink-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{sending ? "Saving..." : "Save collection"}</button></div></form></div>;
}
