import { useState, type FormEvent } from 'react';
import { localDb } from '../../lib/localDb';

export default function EventFavorModal({ slug, onClose }: { slug: string; onClose: () => void }) {
  const [form, setForm] = useState({ name: '', email: '', quantity: 24, vessel: '4 oz tin', scent: '', label_text: '', packaging: 'Individual kraft box', event_date: '', details: '' });
  const [status, setStatus] = useState('');
  const estimate = form.quantity * 8;
  async function submit(event: FormEvent) { event.preventDefault(); try { await localDb.submitEventFavorRequest(slug, form); setStatus('Event favor request sent for review and final quote.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to send request.'); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={(event) => void submit(event)} className="mx-auto my-8 w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">Event favors</h2><p className="mt-1 text-sm text-slate-600">Plan wedding, party, memorial, or corporate candle favors.</p></div><button type="button" onClick={onClose} className="text-sm font-semibold text-pink-700">Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required placeholder="Your name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border p-2" /><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded-lg border p-2" /><input required min="12" type="number" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) })} className="rounded-lg border p-2" /><select value={form.vessel} onChange={(e) => setForm({ ...form, vessel: e.target.value })} className="rounded-lg border p-2"><option>4 oz tin</option><option>6 oz glass jar</option><option>8 oz glass jar</option></select><input required placeholder="Scent direction" value={form.scent} onChange={(e) => setForm({ ...form, scent: e.target.value })} className="rounded-lg border p-2" /><input placeholder="Event date" type="date" value={form.event_date} onChange={(e) => setForm({ ...form, event_date: e.target.value })} className="rounded-lg border p-2" /><input placeholder="Label text" value={form.label_text} onChange={(e) => setForm({ ...form, label_text: e.target.value })} className="rounded-lg border p-2" /><select value={form.packaging} onChange={(e) => setForm({ ...form, packaging: e.target.value })} className="rounded-lg border p-2"><option>Individual kraft box</option><option>Ribbon wrap</option><option>Premium gift box</option></select></div><textarea placeholder="Color, theme, delivery, or other details" value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} className="mt-3 w-full rounded-lg border p-2" rows={3} /><p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Planning estimate: ${estimate.toFixed(2)} before final design, tax, and delivery. We will send a final quote.</p>{status ? <p className="mt-3 text-sm text-emerald-700">{status}</p> : null}<button className="mt-4 w-full rounded-lg bg-pink-600 p-3 font-semibold text-white">Request event favor quote</button></form></div>;
}
