import { useState, type FormEvent } from 'react';
import { localDb, type StorefrontProductSummary } from '../../lib/localDb';

export default function GiftRegistryModal({ slug, token, products, onClose }: { slug: string; token: string; products: StorefrontProductSummary[]; onClose: () => void }) {
  const [title, setTitle] = useState(''); const [eventDate, setEventDate] = useState(''); const [message, setMessage] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [status, setStatus] = useState('');
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = await localDb.createStoreGiftRegistry(slug, token, { title, event_date: eventDate, message, product_ids: selected }); const link = `${window.location.origin}${window.location.pathname}?registry=${result.share_code}`; setStatus(`Registry saved. Share this link: ${link}`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to create registry.'); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={submit} className="store-customer-modal mx-auto my-8 w-full max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">Create a gift registry</h2><p className="mt-1 text-sm text-slate-600">Choose items and share the generated link with friends and family.</p></div><button type="button" onClick={onClose} className="text-sm font-semibold text-pink-700">Close</button></div>{status ? <p className="mt-4 break-all rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{status}</p> : null}<div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Registry title" value={title} onChange={(e) => setTitle(e.target.value)} className="rounded-lg border p-2" /><input type="date" value={eventDate} onChange={(e) => setEventDate(e.target.value)} className="rounded-lg border p-2" /></div><textarea placeholder="Optional message" value={message} onChange={(e) => setMessage(e.target.value)} className="mt-3 w-full rounded-lg border p-2" rows={3} /><div className="mt-4 grid gap-2 sm:grid-cols-2">{products.filter((p) => p.product_type !== 'gift_card').map((product) => <label key={product.id} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(product.id)} onChange={() => toggle(product.id)} /><span><strong>{product.name}</strong><br />${Number(product.price).toFixed(2)}</span></label>)}</div><button disabled={!selected.length} className="mt-5 w-full rounded-lg bg-pink-600 p-3 font-semibold text-white disabled:opacity-50">Create registry</button></form></div>;
}
