import { useEffect, useState, type FormEvent } from 'react';
import { localDb, type StorefrontProductSummary } from '../../lib/localDb';

export default function ProductReviewModal({ slug, token, product, onClose }: { slug: string; token: string; product: StorefrontProductSummary; onClose: () => void }) {
  const [reviews, setReviews] = useState<Array<{ id: string; rating: number; title: string; body: string; photo_data: string; verified_purchase: boolean; customer_name: string; created_at: string }>>([]);
  const [form, setForm] = useState({ rating: 5, title: '', body: '', photo_data: '' }); const [status, setStatus] = useState('');
  useEffect(() => { void localDb.getStoreProductReviews(slug, product.id).then(setReviews).catch(() => setReviews([])); }, [slug, product.id]);
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = await localDb.submitStoreProductReview(slug, token, { ...form, product_id: product.id }); setStatus(result.verified_purchase ? 'Review submitted for moderation. Your purchase was verified.' : 'Review submitted for moderation.'); setForm({ rating: 5, title: '', body: '', photo_data: '' }); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to submit review.'); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><section className="store-customer-modal mx-auto my-8 w-full max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">Reviews for {product.name}</h2></div><button type="button" onClick={onClose} className="text-sm font-semibold text-pink-700">Close</button></div><form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border p-4"><select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })} className="rounded border p-2">{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} star{rating === 1 ? '' : 's'}</option>)}</select><input placeholder="Review title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="rounded border p-2" /><textarea required minLength={10} placeholder="Share your experience" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} className="rounded border p-2" rows={4} /><input placeholder="Optional photo data URL" value={form.photo_data} onChange={(e) => setForm({ ...form, photo_data: e.target.value })} className="rounded border p-2" /><button className="rounded bg-pink-600 p-2 font-semibold text-white">Submit for review</button>{status ? <p className="text-sm text-slate-700">{status}</p> : null}</form><div className="mt-5 space-y-3">{reviews.length ? reviews.map((review) => <article key={review.id} className="rounded-xl border p-4 text-sm"><p className="font-bold text-amber-600">{'*'.repeat(review.rating)} {review.verified_purchase ? <span className="ml-2 text-xs text-emerald-700">Verified purchase</span> : null}</p><p className="mt-1 font-semibold">{review.title || 'Customer review'}</p><p>{review.body}</p>{review.photo_data ? <img src={review.photo_data} alt="Customer review" className="mt-3 max-h-48 rounded" /> : null}<p className="mt-2 text-xs text-slate-500">{review.customer_name}</p></article>) : <p className="text-sm text-slate-500">No approved reviews yet.</p>}</div></section></div>;
}
