import { type FormEvent, useEffect, useState } from 'react';
import { localDb } from '../../lib/localDb';

type Program = { discount_percent: number; eligibility_rules: string; return_instructions: string };
export default function RefillRequestModal({ slug, onClose }: { slug: string; onClose: () => void }) {
  const [program, setProgram] = useState<Program | null>(null); const [message, setMessage] = useState(''); const [form, setForm] = useState({ name: '', email: '', product_name: '', scent: '', quantity: 1, container_condition: 'clean_intact' as 'clean_intact' | 'minor_wear' | 'damaged', details: '' });
  useEffect(() => { void localDb.getPublicRefillProgram(slug).then(setProgram).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Refills are not available.')); }, [slug]);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); try { const result = await localDb.submitPublicRefillRequest(slug, form); setMessage(`Refill request received. Your ${result.discount_percent}% refill discount will be verified once the container is inspected.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to submit refill request.'); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={(event) => void submit(event)} className="mx-auto my-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Candle Refill Program</h2><p className="mt-1 text-sm">Return an eligible container and request a refill.</p></div><button type="button" onClick={onClose} className="text-pink-700">Close</button></div>{program ? <div className="mt-4 rounded border bg-slate-50 p-3 text-sm"><strong>{Number(program.discount_percent)}% refill discount</strong><p className="mt-1">{program.eligibility_rules}</p><p className="mt-2">{program.return_instructions}</p></div> : null}<div className="mt-4 grid gap-3"><input required placeholder="Your name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="rounded border p-2" /><input required type="email" placeholder="Email address" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="rounded border p-2" /><input required placeholder="Original candle or container" value={form.product_name} onChange={(event) => setForm({ ...form, product_name: event.target.value })} className="rounded border p-2" /><input placeholder="Requested refill scent" value={form.scent} onChange={(event) => setForm({ ...form, scent: event.target.value })} className="rounded border p-2" /><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Containers<input required type="number" min="1" max="24" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: Number(event.target.value) })} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-medium">Condition<select value={form.container_condition} onChange={(event) => setForm({ ...form, container_condition: event.target.value as typeof form.container_condition })} className="mt-1 w-full rounded border p-2"><option value="clean_intact">Clean and intact</option><option value="minor_wear">Minor wear</option><option value="damaged">Damaged</option></select></label></div><textarea value={form.details} onChange={(event) => setForm({ ...form, details: event.target.value })} placeholder="Any container details or requests" rows={3} className="rounded border p-2" />{message ? <p className="text-sm">{message}</p> : null}<button disabled={!program || !!message} className="rounded bg-pink-600 p-3 font-semibold text-white disabled:opacity-60">Request a refill</button></div></form></div>;
}
