import { useState } from "react";
import type { StorefrontProductSummary } from "../../lib/localDb";

export default function SamplePackModal({ products, onClose, onAdd }: { products: StorefrontProductSummary[]; onClose: () => void; onAdd: (productId: string) => void }) {
  const [packSize, setPackSize] = useState(2);
  const [selected, setSelected] = useState<string[]>([]);
  const samples = products.filter((product) => product.product_type === "sample" && product.quantity_in_stock > 0);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < packSize ? [...current, id] : current);
  const setSize = (size: number) => { setPackSize(size); setSelected((current) => current.slice(0, size)); };
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><section className="store-customer-modal mx-auto my-8 w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-gray-900">Build a discovery pack</h2><p className="mt-1 text-sm text-gray-600">Choose 2.5 oz sample candles to explore new scents.</p></div><button type="button" onClick={onClose} className="text-sm font-semibold text-pink-700">Close</button></div><div className="mt-4 flex gap-2">{[2, 4, 6, 8].map((size) => <button type="button" key={size} onClick={() => setSize(size)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${packSize === size ? "bg-pink-600 text-white" : "border-gray-300 text-gray-700"}`}>{size} candles</button>)}</div>{samples.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{samples.map((product) => <label key={product.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${selected.includes(product.id) ? "border-pink-600 bg-pink-50" : "border-gray-200"}`}><input type="checkbox" checked={selected.includes(product.id)} onChange={() => toggle(product.id)} className="accent-pink-600" /><div className="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">{product.image_data ? <img src={product.image_data} alt="" className="h-full w-full object-cover" /> : null}</div><div><p className="font-semibold text-gray-900">{product.name}</p><p className="text-sm text-gray-600">2.5 oz candle | ${Number(product.price).toFixed(2)} each</p></div></label>)}</div> : <p className="mt-5 text-sm text-gray-600">This store has no in-stock sample products yet.</p>}<div className="mt-5 flex items-center justify-between border-t border-gray-200 pt-4"><p className="text-sm text-gray-600">{selected.length} of {packSize} selected</p><button type="button" disabled={selected.length !== packSize} onClick={() => { selected.forEach(onAdd); onClose(); }} className="rounded-lg bg-pink-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Add discovery pack to cart</button></div></section></div>;
}
