import { useEffect, useState } from 'react';
import { localDb, type StoreScentPollRecord } from '../../lib/localDb';

const keyFor = (slug: string) => `candles.store.poll-visitor.${slug}`;
function getVisitorKey(slug: string) { let value = localStorage.getItem(keyFor(slug)); if (!value) { value = crypto.randomUUID(); localStorage.setItem(keyFor(slug), value); } return value; }
export default function ScentPollBanner({ slug }: { slug: string }) {
  const [polls, setPolls] = useState<StoreScentPollRecord[]>([]);
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState('');
  const load = async () => { try { setPolls((await localDb.getStoreLaunchTools(slug, getVisitorKey(slug))).polls); } catch { setPolls([]); } };
  useEffect(() => { void localDb.getStoreLaunchTools(slug, getVisitorKey(slug)).then((data) => setPolls(data.polls)).catch(() => setPolls([])); }, [slug]);
  async function vote(poll: StoreScentPollRecord, option: string) { try { await localDb.voteStoreScentPoll(slug, poll.id, option, getVisitorKey(slug)); setMessage('Your vote was updated. Thank you for helping choose the next scent.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to record your vote.'); } }
  if (!polls.length) return null;
  const label = polls.some((poll) => poll.poll_type === 'retired_scent') ? 'Vote on scent releases' : 'Vote for the next scent';
  const remaining = polls.filter((poll) => !poll.voted_option).length;
  return <><div className="app-theme border-y border-pink-200 bg-pink-50 px-4 py-3"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-center gap-3 text-center"><p className="scent-poll-heading font-semibold">{label}</p><p className="text-sm text-pink-800">Help shape what we pour next.</p><button type="button" onClick={() => setOpen(true)} className="relative rounded-full bg-pink-600 px-4 py-2 text-sm font-bold text-white hover:bg-pink-700">Open poll{remaining ? <span className="absolute -right-2 -top-2 grid h-5 min-w-5 place-items-center rounded-full bg-gray-900 px-1 text-[11px] text-white ring-2 ring-pink-50">{remaining}</span> : null}</button></div></div>{open ? <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><section className="mx-auto my-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-gray-900">Scent voting</h2><p className="mt-1 text-sm text-gray-600">Choose one option in each active poll.</p></div><button type="button" onClick={() => setOpen(false)} className="text-sm font-semibold text-pink-700">Close</button></div>{message ? <p className="mt-4 rounded-lg bg-pink-50 p-3 text-sm text-pink-900">{message}</p> : null}<div className="mt-5 space-y-5">{polls.map((poll) => <div key={poll.id} className="border-t border-gray-200 pt-4 first:border-0 first:pt-0"><p className="text-xs font-bold uppercase tracking-wide text-pink-700">{poll.poll_type === 'retired_scent' ? 'Bring back a retired scent' : 'Next scent poll'}</p><h3 className="mt-1 font-bold text-gray-900">{poll.title}</h3><div className="mt-3 flex flex-wrap gap-2">{(poll.options || []).map((option) => <button key={option.name} type="button" onClick={() => void vote(poll, option.name)} className={`rounded-full border px-3 py-2 text-sm font-semibold ${poll.voted_option === option.name ? 'border-pink-600 bg-pink-600 text-white' : 'border-pink-300 text-pink-700 hover:bg-pink-50'}`}>{option.name} <span className={poll.voted_option === option.name ? 'text-pink-100' : 'text-pink-500'}>({option.votes})</span></button>)}</div></div>)}</div></section></div> : null}</>;
}
