import { type FormEvent, useState } from 'react';
import { localDb } from '../../lib/localDb';

export default function WorkshopPartyRequestModal({ slug, onClose }: { slug: string; onClose: () => void }) {
  const [form, setForm] = useState({ name: '', email: '', event_type: 'birthday' as 'birthday' | 'date_night' | 'bridal_party' | 'corporate' | 'other', requested_date: '', party_size: 4, details: '' });
  const [message, setMessage] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); try { await localDb.submitWorkshopPartyRequest(slug, form); setMessage('Your private-party request was sent. The store will contact you with availability and pricing.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to send your party request.'); } }
  return <div className="app-theme fixed inset-0 z-[80] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={(event) => void submit(event)} className="mx-auto my-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Plan a Candle-Making Party</h2><p className="mt-1 text-sm">For birthdays, date nights, bridal parties, and corporate groups of four or more.</p></div><button type="button" onClick={onClose} className="text-pink-700">Close</button></div><div className="mt-4 grid gap-3"><input required placeholder="Your name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="rounded border p-2" /><input required type="email" placeholder="Email address" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="rounded border p-2" /><label className="text-sm font-medium">Event type<select value={form.event_type} onChange={(event) => setForm({ ...form, event_type: event.target.value as typeof form.event_type })} className="mt-1 w-full rounded border p-2"><option value="birthday">Birthday</option><option value="date_night">Date night</option><option value="bridal_party">Bridal party</option><option value="corporate">Corporate group</option><option value="other">Other</option></select></label><label className="text-sm font-medium">Preferred date<input type="date" value={form.requested_date} onChange={(event) => setForm({ ...form, requested_date: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-medium">Guests<input required type="number" min="4" max="100" value={form.party_size} onChange={(event) => setForm({ ...form, party_size: Number(event.target.value) })} className="mt-1 w-full rounded border p-2" /></label><textarea value={form.details} onChange={(event) => setForm({ ...form, details: event.target.value })} placeholder="Tell us about the event, preferred time, and any special requests." rows={4} className="rounded border p-2" />{message ? <p className="text-sm">{message}</p> : null}<button disabled={!!message} className="rounded bg-pink-600 p-3 font-semibold text-white disabled:opacity-60">Request private party</button></div></form></div>;
}
